<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// TODO This would be better if we rename the option keys at the form so these functions can automate adding the styles to the header

 function cyberchimps_css_styles() {
	$body_styles = cyberchimps_body_styles(); 
  $link_styles = cyberchimps_link_styles();?>
  
  <style type="text/css" media="all">
	<?php if ( !empty( $body_styles ) ) : ?>
  body {
    	<?php foreach( $body_styles as $key => $body_style ): ?>
      	<?php echo $key; ?>: <?php echo $body_style; ?>;     
    	<?php endforeach; ?>
  }
  <?php endif; ?>
  <?php if ( !empty( $link_styles ) ) : ?>
  	<?php foreach( $link_styles as $key2 => $link_style ): ?>
  <?php echo $key2; ?>{
    color: <?php echo $link_style; ?>;
  }
  <?php endforeach; ?>
  <?php endif; ?>
  </style>
<?php
	return;
}
add_action( 'wp_head', 'cyberchimps_css_styles', 10 );

function cyberchimps_body_styles() {
	$body_styles = array();
	if ( cyberchimps_get_option( 'background_colorpicker' ) ) {
		$body_styles['background-color'] = cyberchimps_get_option( 'background_colorpicker' );
	}
	if ( cyberchimps_get_option( 'text_colorpicker' ) ) {
		$body_styles['color'] = cyberchimps_get_option( 'text_colorpicker' );
	}
	if ( cyberchimps_get_option( 'typography_options' ) ) {
		$typography_options = cyberchimps_get_option( 'typography_options' );
		foreach( $typography_options as $option => $value ) {
			if( $option == 'size' ) { $option = 'font-size'; }
			if( $option == 'face' ) { $option = 'font-family'; }
			if( $option == 'style' ) { $option = 'font-weight'; }
			if( $value != '' ) {
				$body_styles[$option] = $value;
			}
		}
	}
	
	return $body_styles;
}

function cyberchimps_link_styles() {
	$link_styles = array();
	if ( cyberchimps_get_option( 'link_colorpicker' ) ) {
		$link_styles['a'] = cyberchimps_get_option( 'link_colorpicker' );
	}
	if ( cyberchimps_get_option( 'link_hover_colorpicker' ) ) {
		$link_styles['a:hover'] = cyberchimps_get_option( 'link_hover_colorpicker' );
	}
	
	return $link_styles;
}