<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since	 1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// TODO: Fix documentation
// TODO: Declare all directory constants for core
// TODO: Not sure if I want to actually do it this way just yet
function response_get_core_directory_uri() {
	echo get_template_directory_uri() . '/core';
}

// TODO: Fix documentation
// Enqueue core scripts and core styles
function response_core_scripts() {
	global $post;

	// Load Bootstrap Library Items
	wp_enqueue_style( 'bootstrap-styles', get_template_directory_uri() . '/core/lib/bootstrap/css/bootstrap.min.css', false, '2.0.4' );
	wp_enqueue_style( 'bootstrap-responsive-styles', get_template_directory_uri() . '/core/lib/bootstrap/css/bootstrap-responsive.min.css', array('bootstrap-styles'), '2.0.4' );
	wp_enqueue_script( 'bootstrap-js', get_template_directory_uri() . '/core/lib/bootstrap/js/bootstrap.min.js', array( 'jquery' ), '2.0.4', true );
	
	// Load Theme Stylesheet
	wp_enqueue_style( 'style', get_stylesheet_uri(), array('bootstrap-responsive-styles', 'bootstrap-styles'), '1.0' );
}
add_action( 'wp_enqueue_scripts', 'response_core_scripts', 20 );


// TODO: Fix documentation
// Register our sidebars and widgetized areas.
function response_footer_widgets_init() {
	register_sidebar( array(
		'name' => 'Footer Widgets',
		'id' => 'response_footer_widgets',
		'before_widget' => '<div class="span3">',
		'after_widget' => '</div>',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
	
	// TODO: Update this code to be cleaner
	register_sidebar(array(
		'name' => __( 'Sidebar' ),
		'id' => 'sidebar',
		'description' => __( 'Widgets in this area will be shown on the right-hand side.' ),
		'before_widget' => '<div class="row-fluid">',
		'after_widget' => '</div>',
		'before_title' => '<h1>',
		'after_title' => '</h1>'
	));
}
add_action( 'widgets_init', 'response_footer_widgets_init' );


// TODO: Fix documentation
// TODO: Rename and rework function
function response_add_site_info() { ?>
	<p>&copy; Company Name</p>	
<?php }
add_action('response_site_info', 'response_add_site_info');


// TODO: Create generic functions that will be used for all themes

