<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

if ( ! function_exists( 'response_core_setup_theme' ) ):
// FIXME: Fix documentation
function response_core_setup_theme() {
	
	// TODO: Fix documentation
	// Load core functions file
	require_once( get_template_directory() . '/core/functions.php' );
	
	// TODO: Fix documentation
	// Load core hooks file
	require_once( get_template_directory() . '/core/inc/hooks.php' );
	
	// FIXME: Fix documentation
	// Load core options file
	require_once( get_template_directory() . '/core/inc/options.php' );

	/**
	 * Custom template tags for this theme.
	 */
	// TODO: require( get_template_directory() . '/inc/template-tags.php' );

	/**
	 * Custom functions that act independently of the theme templates
	 */
	//require( get_template_directory() . '/inc/tweaks.php' );

	// Core Translations can be filed in the /inc/languages/ directory
	load_theme_textdomain( 'response', get_template_directory() . '/lib/languages' );
	
	// Add support for the Aside Post Formats
	add_theme_support( 'post-formats', array( 'aside' ) );
	
	// Add default posts and comments RSS feed links to head
	add_theme_support( 'automatic-feed-links' );

	// Enable support for Post Thumbnails
	add_theme_support( 'post-thumbnails' );
	
	/**
	 * This theme uses wp_nav_menu() in one location.
	 */
	register_nav_menus( array(
		'primary' => __( 'Primary Menu', 'response' ),
	) );
}
endif; // response_core_setup_theme
add_action( 'after_setup_theme', 'response_core_setup_theme' );


// FIXME: Fix documentation
function response_core_init() {
	
}
add_action( 'init', 'response_core_init' );


// FIXME: Fix documentation
function response_core_admin_init() {
	
}
add_action( 'admin_init', 'response_core_admin_init' );

// FIXME: Fix documentation
// Register our sidebars and widgetized areas.
function response_widgets_init() {
	register_sidebar( array(
		'name' => __( 'Sidebar Left', 'response' ),
		'id' => 'sidebar-left',
		'before_widget' => '<aside id="%1$s" class="widget row-fluid %2$s">',
		'after_widget' => "</aside>",
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	));
	
	register_sidebar( array(
		'name' => __( 'Sidebar-Right', 'response' ),
		'id' => 'sidebar-right',
		'before_widget' => '<aside id="%1$s" class="widget row-fluid %2$s">',
		'after_widget' => "</aside>",
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	));
	
	register_sidebar( array(
		'name' => __( 'Footer Widgets', 'response' ),
		'id' => 'response-footer-widgets',
		'before_widget' => '<aside id="%1$s" class="widget span3 %2$s">',
		'after_widget' => "</aside>",
		'before_title' => '<h3 class="widget-title">',
		'after_title' => '</h3>',
	));
}
add_action( 'widgets_init', 'response_widgets_init' );


// FIXME: Fix documentation
// Load elements
function response_load_elements() {
	
	// TODO: Find out which elements are enabled by theme true is enabled and false is disabled
	$options = array( 'callout' => true, 'twitter-bar' => true, 'breadcrumbs' => true );
	
	if ( $options['callout'] ) {
		require_once( get_template_directory() . '/core/elements/callout.php' );
	}
	
	if ( $options['twitter-bar'] ) {
		require_once( get_template_directory() . '/core/elements/twitter-bar.php' );
	}
	
	if ( $options['breadcrumbs'] ) {
		require_once( get_template_directory() . '/core/elements/breadcrumbs.php' );
	}	
}
add_action('after_setup_theme', 'response_load_elements');
