<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

if ( !class_exists( 'CyberChimpsCarousel' ) ) {
	class CyberChimpsCarousel {
		
		protected static $instance;
		
		/* Static Singleton Factory Method */
		public static function instance() {
			if (!isset(self::$instance)) {
				$className = __CLASS__;
				self::$instance = new $className;
			}
			return self::$instance;
		}	
		
		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct( ) {
			//add_action( 'init', array( $this, 'init'), 10 );
			// TODO: Remove - Just for styling
			// add_action( 'cyberchimps_before_content', array( $this, 'render_display' ) );
			// TODO: Remove - Just for styling
			add_action( 'cyberchimps_before_container', array( $this, 'render_display' ) );
		}
		
		/**
		 * Run on applied action init
		 */
		public function init() {
		}
		
		// TODO: Fix documentation
		public function render_display() {
			$tmp_query = $wp_query; 
			$default = get_template_directory_uri() . '/core/lib/images/carousel.jpg';

			if ( is_page() ) {
				$customcategory = get_post_meta($post->ID, 'carousel_category' , true);
			}
			?>
			<div class="carousel">
				<div class="row-fluid">
					<div class="span12">
						<?php
						// TODO: Convert to get_posts()
						query_posts( array ('post_type' => 'cyberchimps_carousel', 'showposts' => 50, true, 'carousel_categories' => $customcategory ));
						
						if (have_posts()) :
							$out = '<ul>';
							
							while ( have_posts() ) : 
								the_post();
								
								/* Post-specific variables */
								$image = get_post_meta($post->ID, 'post_image', true);
								$realtitle = get_the_title();
								$link = get_post_meta($post->ID, 'post_url', true);
								
								if ( $realtitle != 'Untitled' ) {
									$title = get_the_title();
								} else {
									$title =  '';
								}
								
								if ($image == '') {
									$image = $default;
								}
								
								$out .= '<li>';
								$out .= '<a href="'.$link.'"><img src='.$image.'" alt="'.$title.'"/></a>';
								$out .= '<div class="carousel_caption">'.$title.'</div>';
								$out .= '</li>';
							
							endwhile;	
							$out .= '</ul>';
							
						else :
							$out .= '<ul>';
								$out .= '<li>';
								$out .= '<img src="'.$default.'" alt="Post 1"/>';
								$out .= '</li>';
								$out .= '<li>';
								$out .= '<img src="'.$default.'" alt="Post 2"/>';
								$out .= '</li>';
								$out .= '<li>';
								$out .= '<img src="'.$default.'" alt="Post 3"/>';
								$out .= '</li>';
								$out .= '<li>';
								$out .= '<img src="'.$default.'" alt="Post 4"/>';
								$out .= '</li>';
								$out .= '<li>';
								$out .= '<img src="'.$default.'" alt="Post 5"/>';
								$out .= '</li>';
								$out .= '<li>';
								$out .= '<img src="'.$default.'" alt="Post 6"/>';
								$out .= '</li>';
								$out .= '<li>';
								$out .= '<img src="'.$default.'" alt="Post 7"/>';
								$out .= '</li>';
								$out .= '<li>';
								$out .= '<img src="'.$default.'" alt="Post 8"/>';
								$out .= '</li>';
							$out .= '</ul>';
						endif;
						
						$wp_query = $tmp_query;
						wp_reset_query(); /* Reset post query */
						
						echo $out;
						?>
					</div>
				</div>
			</div>
			<?php
		}
	}
}
CyberChimpsCarousel::instance();