<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

add_action( 'magazine', 'magazine_element_content' );

// Defining contents of the magazine post element
function magazine_element_content() {
	global  $post;  // call globals	

	// Getting metabox options
	$column_no = get_post_meta($post->ID, 'cyberchimps_magazine_no_of_columns' , true);
	$column_no += 2;
	
	$row_no = get_post_meta($post->ID, 'cyberchimps_magazine_no_of_rows' , true);
	$row_no += 1;
	
	$wide_post =  get_post_meta($post->ID, 'cyberchimps_magazine_wide_post_toggle' , true);
	$wide_post_no = get_post_meta($post->ID, 'cyberchimps_magazine_no_of_wide_posts' , true);
	$wide_post_no += 1;
	
	$meta_toggle = get_post_meta($post->ID, 'cyberchimps_magazine_meta_data_toggle' , true);
?>
	<div class="row-fluid">
		<?php
		$magazine = new WP_Query(
								array(
									'paged'         => $page_number,
									'post_type'     => 'post',
									'orderby'       => 'post_date',
									'order'         => 'desc',
									'post__not_in'  => $exclude_posts
									)
								);
		?>
		
		<div id="content">
			<div class="row-fluid">
				
				<?php
					/* Initializing counters. */
					$counter_post = 0; 
					$counter_box = 0;
					$counter_wide = 0;
					
				if ($magazine -> have_posts()) : while ($magazine -> have_posts()) : $magazine -> the_post();
					if( $counter_post < ( $row_no * $column_no ) )
					{ ?>
						<div class="post_container box_post span4">            
							<div <?php post_class() ?> id="post-<?php the_ID(); ?>">                
								<?php                
								if (get_post_format() == '') {
									$format = "default";
								}
								else {
									$format = get_post_format();
								} ?>
							
								<!-- Display Title -->
								<h2 class="posts_title"><a href="<?php the_permalink() ?>"><?php the_title(); ?></a></h2>
								
								<!-- Display Thumbnail -->
								<?php
								if ( has_post_thumbnail() ) {
									echo '<div class="featured-image">';
									echo '<a href="' . get_permalink($post->ID) . '" >';
										the_post_thumbnail('thumbnail');
									echo '</a>';
									echo '</div>';
								}
								?>	
								
								<!-- Display Metadata -->
								<?php
								if( $meta_toggle == 1 )
								{
									echo "Published on "; ?> <a href="<?php the_permalink() ?>"><?php echo get_the_date(); ?></a>
									<?php
									echo " by "; the_author_posts_link();
									echo " in "; the_category(', ');
								}
								?>
		
								<div class="entry" <?php if ( has_post_thumbnail() ) { echo 'style="min-height: 115px;" '; }?>>
									<?php 
									add_filter('excerpt_more', 'featured_post_excerpt_more');
									add_filter( 'excerpt_length', 'featured_post_length', 999 );
									the_excerpt();
									remove_filter('excerpt_more', 'featured_post_excerpt_more');
									remove_filter( 'excerpt_length', 'featured_post_length', 999);
									?>
								</div><!--end entry-->  
							
								<div id="comments">
									<span class="comments-n-views"><?php comments_popup_link('No Comment', '1 Comment', '% Comments');?></span>
								</div>
								
								<!-- ************bottom bar*********** -->	
								<div class="socialbar">
								</div>
														
							</div><!--end post_class-->
						</div><!--end post container-->
						<?php 
						$counter_box++;
						$counter_post++;
						if($column_no == $counter_box) {
							echo '</div><div class="row-fluid">';
							$counter_box = 0;
						}
						
						if( $counter_post == 6 && $column_no == 3 )
						{ ?>
							</div> </div> </div>	<!-- Ending "row-fluid" and "content" div -->
							
							<!-- Starting "content" and "row-fluid" div -->
							<div class="row-fluid">	
								<div id="content">
									<div class="row-fluid">	
						<?php
						}
					}
					else
					{ 
						if( ( $wide_post == 1 ) && ( $counter_wide < $wide_post_no ) )
						{
					?>
						<div class="post_container wide_post span8">
							<div <?php post_class() ?> id="post-<?php the_ID(); ?>">
							
								<!-- Display Title -->
								<h2 class="posts_title"><a href="<?php the_permalink() ?>"><?php the_title(); ?></a></h2>
								
								<!-- Display Thumbnail -->
								<?php
								if ( has_post_thumbnail() ) {
									echo '<div class="featured-image">';
									echo '<a href="' . get_permalink($post->ID) . '" >';
										the_post_thumbnail('thumbnail');
									echo '</a>';
									echo '</div>';
								}
								?>
								
								<!-- Display Metadata -->
								<?php
								if( $meta_toggle == 1 )
								{
									echo "Published on "; ?> <a href="<?php the_permalink() ?>"><?php echo get_the_date(); ?></a>
									<?php
									echo " by "; the_author_posts_link();
									echo " in "; the_category(', ');
								}
								?>
								
								<div class="entry" <?php if ( has_post_thumbnail() && $featured_images == '1' ) { echo 'style="min-height: 115px;" '; }?>>
									<?php 
									add_filter('excerpt_more', 'featured_post_excerpt_more');
									add_filter( 'excerpt_length', 'magazine_post_wide', 999 );
									the_excerpt();
									remove_filter('excerpt_more', 'featured_post_excerpt_more');
									remove_filter( 'excerpt_length', 'magazine_post_wide', 999 );
									?>
								</div><!--end entry-->  
								
								<div id="comments">
									<span class="comments-n-views"><?php comments_popup_link('No Comment', '1 Comment', '% Comments');?></span>
								</div>
						
								<!-- ************bottom bar*********** -->	
								<div class="socialbar">
								</div>
								
								</div><!--end post_class-->
						</div><!--end post container-->
					<?php 
						$counter_wide++;
						}
					}
						endwhile;
					else : ?>
						<h2>Not Found</h2>
				<?php endif; ?>
				
			</div><!--end content-->
		</div>
		</div>
<?php	
}
?>