<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since	 1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
// TODO: Fix documentation
// TODO: Tie into an add_action or some other way
function response_portfolio() {
	// TODO: query post get portfolio image details
	
	// TODO: add hooks into markup below and edit variable calls
	
	// TODO: fix portfolio item markup change caption div to span maybe
	?>
	<div id="portfolio" class="container-fluid">
		<div class="row-fluid">
			<div id="gallery" class="span12"><?php echo $title_output; ?>
				<ul>
					<li id="portfolio_wrap" class="span3">
						<a href='<?php echo $img1 ;?>' rel="lightbox-portfolio" title='<?php echo $caption1 ;?>'>
							<img src='<?php echo $img1 ;?>' alt='Image 1'/>
							<div class="portfolio_caption"><?php echo $caption1 ;?></div>
						</a>
					</li><!-- #portfolio_wrap .span3-->
				
			    	<li id="portfolio_wrap" class="span3">
						<a href='<?php echo $img2 ;?>' rel="lightbox-portfolio" title='<?php echo $caption2 ;?>'>
							<img src='<?php echo $img2 ;?>' alt='Image 1'/>
							<div class="portfolio_caption"><?php echo $caption2 ;?></div>
						</a>
					</li><!-- #portfolio_wrap .span3-->
				
					<li id="portfolio_wrap" class="span3">
						<a href='<?php echo $img3 ;?>' rel="lightbox-portfolio" title='<?php echo $caption3 ;?>'>
							<img src='<?php echo $img3 ;?>' alt='Image 1'/>
							<div class="portfolio_caption"><?php echo $caption3 ;?></div>
						</a>
					</li><!-- #portfolio_wrap .span3-->
					
					<li id="portfolio_wrap" class="span3">
						<a href='<?php echo $img4 ;?>' rel="lightbox-portfolio" title='<?php echo $caption4 ;?>'>
							<img src='<?php echo $img4 ;?>' alt='Image 1'/>
							<div class="portfolio_caption"><?php echo $caption4 ;?></div>
						</a>
					</li><!-- #portfolio_wrap .span3-->
				</ul>
			</div><!-- #gallery .span12-->
		</div><!-- .row-fluid-->
	</div><!-- #portfolio .fluid-container-->
	<?php
}