<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }
 
// Portfolio Lite element action
add_action( 'portfolio_lite', 'portfolio_lite_content' );

function portfolio_lite_content() {	
	global $options, $post, $wp_query;
	$tmp_query = $wp_query; 
	$image = get_post_meta($post->ID, 'portfolio_image' , true);
	
	if (is_page()) {
		$title_enable = get_post_meta($post->ID, 'cyberchimps_portfolio_title_toggle' , true);
		$title = get_post_meta($post->ID, 'cyberchimps_portfolio_title' , true);
	
		$img1 = get_post_meta($post->ID, 'cyberchimps_portfolio_lite_image_one' , true);
		$img2 = get_post_meta($post->ID, 'cyberchimps_portfolio_lite_image_two' , true);
		$img3 = get_post_meta($post->ID, 'cyberchimps_portfolio_lite_image_three' , true);
		$img4 = get_post_meta($post->ID, 'cyberchimps_portfolio_lite_image_four' , true);
	
		$caption1 = get_post_meta($post->ID, 'cyberchimps_portfolio_lite_image_one_caption' , true);
		$caption2 = get_post_meta($post->ID, 'cyberchimps_portfolio_lite_image_two_caption' , true);
		$caption3 = get_post_meta($post->ID, 'cyberchimps_portfolio_lite_image_three_caption' , true);
		$caption4 = get_post_meta($post->ID, 'cyberchimps_portfolio_lite_image_four_caption' , true);
	}
	else {
	
		/*  Need to be changed after theme option is placed 
		$title_enable = $options->get('_blog_portfolio_title_toggle');
		$title = $options->get('_blog_portfolio_title');

		$img1source = $options->get('_blog_portfolio_image_one');
		$img2source = $options->get('_blog_portfolio_image_two');
		$img3source = $options->get('_blog_portfolio_image_three');
		$img4source = $options->get('_blog_portfolio_image_four');
		
		$img1 = $img1source['url'];
		$img2 = $img2source['url'];
		$img3 = $img3source['url'];
		$img4 = $img4source['url'];
	
		$caption1 = $options->get('_blog_portfolio_image_one_caption');
		$caption2 = $options->get('_blog_portfolio_image_two_caption');
		$caption3 = $options->get('_blog_portfolio_image_three_caption');
		$caption4 = $options->get('_blog_portfolio_image_four_caption');   */
	}

	$title = ($title != '') ? $title : 'Portfolio';	
	$title_output = ($title_enable == 'on' OR $title_enable == '1') ? "<h2 class='entry-title'>$title</h1>" : '';
	
	/* Post-specific variables */	
		$image = get_post_meta($post->ID, 'portfolio_image' , true);
		$title = get_the_title() ;		
?>

<div class="row-fluid">
     <div class="portfolio" class="span12">
		<div id="gallery">
			
			<!-- Display the title -->
			<h2 class="entry-title"><?php echo $title_output; ?></h2>
			
			<ul class="row-fluid">
				<li id="portfolio_wrap" class="span3">
					<a href='<?php echo $img1 ;?>' rel="lightbox-portfolio" title='<?php echo $caption1 ;?>'><img src='<?php echo $img1 ;?>'  alt='Image 1'/>
						<div class='portfolio_caption'><?php echo $caption1 ;?></div>
					</a>
				</li>
		
				<li id="portfolio_wrap" class="span3">
					<a href='<?php echo $img2 ;?>' rel="lightbox-portfolio" title='<?php echo $caption2 ;?>'><img src='<?php echo $img2 ;?>'  alt='Image 1'/>
						<div class='portfolio_caption'><?php echo $caption2 ;?></div>
					</a>
				</li>
		
				<li id="portfolio_wrap" class="span3">
					<a href='<?php echo $img3 ;?>' rel="lightbox-portfolio" title='<?php echo $caption3 ;?>'><img src='<?php echo $img3 ;?>'  alt='Image 1'/>
						<div class='portfolio_caption'><?php echo $caption3 ;?></div>
					</a>
				</li>
			
				<li id="portfolio_wrap" class="span3">
					<a href='<?php echo $img4 ;?>' rel="lightbox-portfolio" title='<?php echo $caption4 ;?>'><img src='<?php echo $img4 ;?>'  alt='Image 1'/>
						<div class='portfolio_caption'><?php echo $caption4 ;?></div>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>

<?php
}
?>