<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

if ( !class_exists( 'CyberChimpsPortfolio' ) ) {
	class CyberChimpsPortfolio {
		
		protected static $instance;
		
		/* Static Singleton Factory Method */
		public static function instance() {
			if (!isset(self::$instance)) {
				$className = __CLASS__;
				self::$instance = new $className;
			}
			return self::$instance;
		}	
		
		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct( ) {
			add_action( 'portfolio_pro', array( $this, 'render_display' ) );
		}
		
		// TODO: Fix documentation
		public function render_display() {
			global $options, $post;
			if( is_page() ) {
				$images_per_row = get_post_meta( $post->ID, 'portfolio_row_number', true );
				$portfolio_category = get_post_meta( $post->ID, 'portfolio_category', true );
				$portfolio_title_toggle = get_post_meta( $post->ID, 'portfolio_title_toggle', true );
				$portfolio_title = get_post_meta( $post->ID, 'portfolio_title', true );
			}
			else {
				$images_per_row = $options['cyberchimps_blog_portfolio_pro_per_row'];
				$customcategory_obj = get_term( $options['cyberchimps_blog_portfolio_pro_category'], 'portfolio_cats' );
				$portfolio_category = $customcategory_obj->name;
				$portfolio_title_toggle = $options['cyberchimps_blog_portfolio_pro_title'];
				$portfolio_title = $options['cyberchimps_blog_portfolio_pro_title_text'];
			}
			$args = array(
							'numberposts'     => 500,
							'offset'          => 0,
							'portfolio_cats'	=> $portfolio_category,
							'orderby'         => 'post_date',
							'order'           => 'ASC',
							'post_type'       => 'portfolio_images',
							'post_status'     => 'publish'
							);
			$portfolio_posts = get_posts( $args );
			
			$port_array = array();
			$i = 1;
			switch( $images_per_row ) {
				case 2:
					$span = 'span6';
					break;
				case 3:
					$span = 'span4';
					break;
				case 4:
					$span = 'span3';
					break;
			}?>
      <div id="portfolio" class="row-fluid">
     	 <div id="gallery" class="span12">
          <?php if( $portfolio_title_toggle && $portfolio_title != '' ): ?>
          	<h3><?php echo $portfolio_title; ?></h3>
          <?php endif; ?>
			<?php foreach( $portfolio_posts as $port ):
			
				$image = get_post_meta( $port->ID, 'portfolio_image', true );
				$caption = get_post_meta( $port->ID, 'caption_text', true );
				$link = get_post_meta( $port->ID, 'custom_portfolio_url', true );
				$link_use = get_post_meta( $port->ID, 'custom_portfolio_url_toggle', true );
				$url = ( isset( $link_use ) && $link != '' ) ? $link : $image;
				$rel = ( ! isset( $link_use ) || $link == '' ) ? 'lightbox-portfolio' : '';
				
				if( $i == 1 ): ?>
					<ul class="row-fluid">
				<?php endif;
				if( $i <= $images_per_row ): ?>
        	<li id="portfolio_wrap" class="<?php echo $span; ?>">
          	<div class="portfolio_item">
            <a href="<?php echo $url; ?>" rel="<?php echo $rel; ?>" title="Caption">
              <img src="<?php echo $image ;?>" alt="Image 1"/>
              <div class="portfolio_caption"><?php echo $caption; ?></div>
            </a>
            </div>
					</li><!-- #portfolio_wrap .span3-->
        <?php endif;
				if( $i == $images_per_row ) {
					$i = 1;
					echo '</ul>';
				}
				else {
					$i++;
				}
			
			endforeach; ?>
      
      		</div><!-- #gallery .span12-->
			</div><!-- row-fluid -->
							
			<?php
		}
	}
}
CyberChimpsPortfolio::instance();