<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

// Action for Slider Lite
add_action ('slider_lite', 'slider_lite_content' );

function slider_lite_content() {

	global $options, $wp_query, $post, $slider_default;
		
	if (is_page()) {
		$slide1 = get_post_meta($post->ID, 'cyberchimps_slider_lite_slide_one_image' , true);
		$slide2 = get_post_meta($post->ID, 'cyberchimps_slider_lite_slide_two_image' , true);
		$slide3 = get_post_meta($post->ID, 'cyberchimps_slider_lite_slide_three_image' , true);
	
		$link1 = get_post_meta($post->ID, 'cyberchimps_slider_lite_slide_one_url' , true);
		$link2 = get_post_meta($post->ID, 'cyberchimps_slider_lite_slide_two_url' , true);
		$link3 = get_post_meta($post->ID, 'cyberchimps_slider_lite_slide_three_url' , true);
	}
	
	else {
		
		/* To be modified after integration of element in theme option
		$slide1source = $options->get('_blog_slide_one_image');
		$slide2source = $options->get('_blog_slide_two_image');
		$slide3source = $options->get('_blog_slide_three_image');
		
		$slide1 = $slide1source['url'];
		$slide2 = $slide2source['url'];
		$slide3 = $slide3source['url'];
	
		$link1 = $options->get('_blog_slide_one_url');
		$link2 = $options->get('_blog_slide_two_url');
		$link3 = $options->get('_blog_slide_three_url');

		*/
	}
?>
	<div id="slider-lite" class="carousel slide">
		<div class="carousel-inner">
			<div class="active item">
				<a href="<?php echo $link1; ?>">
					<img src="<?php echo $slide1 ;?>" alt="Slider" />
				</a>
			</div>
			<div class="item">
				<a href="<?php echo $link2; ?>">
					<img src="<?php echo $slide2 ;?>" alt="Slider" />
				</a>
			</div>
			<div class="item">
				<a href="<?php echo $link3; ?>">
					<img src="<?php echo $slide3 ;?>" alt="Slider" />
				</a>
			</div>
		</div>
		
		<!-- Slider nav -->
		<a class="carousel-control left slider-lite-left" href="#slider-lite" data-slide="prev">&lsaquo;</a>
		<a class="carousel-control right slider-lite-right" href="#slider-lite" data-slide="next">&rsaquo;</a>
				
	</div>
<?php
}
?>