<?php
/**
 * Title: Slider Element
 *
 * Description: Slides images from the custom post type slider.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

if ( !class_exists( 'CyberChimpsSlider' ) ) {
	class CyberChimpsSlider {
		
		protected static $instance;
		
		/* Static Singleton Factory Method */
		public static function instance() {
			if (!isset(self::$instance)) {
				$className = __CLASS__;
				self::$instance = new $className;
			}
			return self::$instance;
		}	
		
		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct( ) {
			add_action( 'page_slider', array( $this, 'render_display' ) );
		}
		
		// TODO: Fix documentation
		public function render_display() {
		?>
			<!-- New Slider -->
			<div id="slider" class="carousel slide">
			
				<!-- Carousel items -->
				<div class="carousel-inner">
					<?php
					// Making the query to bring post from custom post type "custom_slides"
					$slider = new WP_Query(
											array(
												'post_type' => 'custom_slides',
												'orderby'   => 'post_date',
												'order'     => 'desc'
												)
											);
					
					//	Setting slide counter					
					$slide_counter = 1;
					
					// Setting the loop to get all slides
					if ($slider -> have_posts()) {
						while ($slider -> have_posts()) {
							$slider -> the_post();
							
							// Getting ID of the current post
							$post_id = get_the_ID();
							
							// Getting metabox options for each slides
							$img_src = get_post_meta($post_id, 'cyberchimps_slider_image' , true);
							$slide_url = get_post_meta($post_id, 'slider_url' , true);
							$caption = get_post_meta($post_id, 'slider_caption' , true);
							
					?>
						<!-- Marup for each slides starts -->
						<!-- Adding class="active" for the first slide -->
						<div class="item <?php echo ( $slide_counter == 1 ) ? "active" : "" ; ?>">
						
							<!-- Slide image -->
							<a href="<?php echo $slide_url; ?>"><img src="<?php echo $img_src; ?>" /></a>
							
							<!-- Display Caption -->
							<div class="carousel-caption">
							  <h4><?php echo $caption; ?></h4>
							</div>
						</div>
						<!-- Marup for each slides ends -->
					
					<?php
						$slide_counter++; 
						}
					}	
					?>
					
				</div>
				
				<!-- Carousel nav -->
				<a class="carousel-control left slider-left" href="#slider" data-slide="prev">&lsaquo;</a>
				<a class="carousel-control right slider-right" href="#slider" data-slide="next">&rsaquo;</a>
			</div>
			<!-- /New Slider -->
			<?php
		}
	}
}
CyberChimpsSlider::instance();