<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

if ( !class_exists( 'CyberChimpsWidgets' ) ) {
	class CyberChimpsWidgets {
		
		protected static $instance;
		
		/* Static Singleton Factory Method */
		public static function instance() {
			if (!isset(self::$instance)) {
				$className = __CLASS__;
				self::$instance = new $className;
			}
			return self::$instance;
		}	
		
		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct( ) {
			add_action( 'widgets_section', array( $this, 'render_display' ) );
		}
		
		// TODO: Fix documentation
		public function render_display() {
			?>
			<div class="row-fluid">
				<div class="boxes">
					<div id="box1" class="box span4">
						<h2 class="box-widget-title">Box Left</h2>
						<p>Collaboratively build intuitive outsourcing before high-quality metrics. Interactively scale client-centric architectures through enterprise-wide "outside the box" thinking. Seamlessly benchmark end-to-end collaboration and idea-sharing and clicks-and-mortar.</p>
					</div><!--end box1-->
	
					<div id="box2" class="box span4">
						<h2 class="box-widget-title">Box Middle</h2>
						<p>This is the box middle widgetized area.</p>
					</div><!--end box2-->
				
					<div id="box3" class="box span4">
						<h2 class="box-widget-title">Box Right</h2>
						<p>This is the box right widgetized area.</p>
					</div><!--end box3-->
				</div><!-- boxes -->
			</div><!-- row-fluid -->
		<?php
		}
	}
}
CyberChimpsWidgets::instance();