/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

function mycarousel_initCallback(carousel)
{
	// Disable autoscrolling if the user clicks the prev or next button.
	carousel.buttonNext.bind('click', function() {
		carousel.startAuto(0);
	});

	carousel.buttonPrev.bind('click', function() {
		carousel.startAuto(0);
	});

	// Pause autoscrolling if the user moves with the cursor over the clip.
	carousel.clip.hover(function() {
		carousel.stopAuto();
	}, function() {
		carousel.startAuto();
	});
};

/*	Initiating jcarousel while page is ready	*/
jQuery(document).ready(function() {
	jQuery('#mycarousel').jcarousel({
		vertical: true,
		auto: 2,
		wrap: 'last',
		initCallback: mycarousel_initCallback
	});
});

/* ************** JS for featured post element *************** */

jQuery(document).ready(function() 
{
jQuery('#featured ul li').click(function(e) 
	{ 
		var id = jQuery(this).attr('id');
		jQuery('#headline li').css("display", "none");
		jQuery('#headline li.' + id).fadeIn('slow');
		
	});
});

/* Initiating slider */
jQuery(document).ready(function() 
{
	jQuery('.carousel').carousel().next();
});