<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// create the admin menu for the theme options page
add_action('admin_menu', 'response_admin_add_customizer_page');
function response_admin_add_customizer_page() {
	// add the Customize link to the admin menu
	add_theme_page( __('Customize', 'response'), __('Customize', 'response'), 'edit_theme_options', 'customize.php' );
}

add_action('customize_register', 'themedemo_customize');
function themedemo_customize($wp_customize) {

	$wp_customize->add_section( 'themedemo_demo_settings', array(
		'title'          => 'Demonstration Stuff',
		'priority'       => 35,
	) );

	$wp_customize->add_setting( 'response_options[core_text]', array(
		'default'        => 'default_value',
		'type'           => 'option',
	) );

	$wp_customize->add_control( 'core_text', array(
		'label'   => 'Text Setting',
		'section' => 'themedemo_demo_settings',
		'type'    => 'text',
		'settings'   => 'response_options[core_text]',
	) );
}
