<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// TODO: this is where we will build our default headings for the options page
function response_add_core_headings( $headings_list ) {
	
	$headings_list = array();
	
	$headings_list[] = array(
		'id' => 'response_welcome_heading',
		'title' => __('Welcome', 'response'),
		'description' => __('Welcome Description', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_design_heading',
		'title' => __('Design', 'response'),
		'description' => __('Design Description', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_header_heading',
		'title' => __('Header', 'response'),
		'description' => __('Header Description', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_blog_heading',
		'title' => __('Blog', 'response'),
		'description' => __('Blog Description', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_templates_heading',
		'title' => __('Templates', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_footer_heading',
		'title' => __('Footer', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_import_export_heading',
		'title' => __('Import/Export', 'response'),
	);
	
	return $headings_list;
}
add_filter('response_heading_list', 'response_add_core_headings');

// TODO: this is where we will build our default sections for the options page
function response_add_core_sections( $sections_list ) {
	
	$sections_list = array();
	/*
	$sections_list[] = array(
		'id' => 'response_temp_styling_section',
		'label' => __('Styling Section', 'response'),
		'heading' => 'response_design_heading'
	);
	*/
	
	$sections_list[] = array(
		'id' => 'response_responsive_section',
		'label' => __('Responsive', 'response'),
		'description' => __('Responsive Description', 'response'),
		'heading' => 'response_design_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_typography_section',
		'label' => __('Typography', 'response'),
		'description' => __('Typography Description', 'response'),
		'heading' => 'response_design_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_background_section',
		'label' => __('Background', 'response'),
		'description' => __('Background Description', 'response'),
		'heading' => 'response_design_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_layout_section',
		'label' => __('Layout', 'response'),
		'description' => __('Layout Description', 'response'),
		'heading' => 'response_design_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_custom_colors_section',
		'label' => __('Custom Colors', 'response'),
		'description' => __('Custom Colors Description', 'response'),
		'heading' => 'response_design_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_custom_css_section',
		'label' => __('Custom CSS', 'response'),
		'description' => __('Custom CSS Description', 'response'),
		'heading' => 'response_design_heading'
	);
	
	/* HEADER */
	
	$sections_list[] = array(
		'id' => 'response_header_drag_drop_section',
		'label' => __('Header Drag/Drop', 'response'),
		'description' => __('Header Drag/Drop Description', 'response'),
		'heading' => 'response_header_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_header_options_section',
		'label' => __('Header Options', 'response'),
		'description' => __('Header Options description', 'response'),
		'heading' => 'response_header_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_header_imenu_section',
		'label' => __('iMenu Options', 'response'),
		'description' => __('iMenu Options description', 'response'),
		'heading' => 'response_header_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_header_social_section',
		'label' => __('Social', 'response'),
		'description' => __('Social description', 'response'),
		'heading' => 'response_header_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_header_scripts_section',
		'label' => __('Tracking and Scripts', 'response'),
		'description' => __('Tracking and Scripts description', 'response'),
		'heading' => 'response_header_heading'
	);
	
	/* BLOG */
	
	$sections_list[] = array(
	'id' => 'response_blog_drag_and_drop_section',
		'label' => __('Drag & Drop', 'response'),
		'description' => __('Drag & drop description', 'response'),
		'heading' => 'response_blog_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_blog_options_section',
		'label' => __('Blog Options', 'response'),
		'description' => __('Options description', 'response'),
		'heading' => 'response_blog_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_blog_slider_section',
		'label' => __('Blog Slider', 'response'),
		'description' => __('Slider description', 'response'),
		'heading' => 'response_blog_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_blog_seo_section',
		'label' => __('SEO', 'response'),
		'description' => __('SEO description', 'response'),
		'heading' => 'response_blog_heading'
	);
	
	/* TEMPLATE */
	
	$sections_list[] = array(
	'id' => 'response_single_post_section',
		'label' => __('Single Post', 'response'),
		'description' => __('Single Post description', 'response'),
		'heading' => 'response_templates_heading'
	);
		
	$sections_list[] = array(
	'id' => 'response_archive_section',
		'label' => __('Archive', 'response'),
		'description' => __('Archive description', 'response'),
		'heading' => 'response_templates_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_search_section',
		'label' => __('Search', 'response'),
		'description' => __('Search description', 'response'),
		'heading' => 'response_templates_heading'
	);
	
	$sections_list[] = array(
	'id' => 'response_error_section',
		'label' => __('404', 'response'),
		'description' => __('404 description', 'response'),
		'heading' => 'response_templates_heading'
	);
	
	/* FOOTER */
	
	$sections_list[] = array(
	'id' => 'response_footer_section',
		'label' => __('Footer Options', 'response'),
		'description' => __('Footer description', 'response'),
		'heading' => 'response_footer_heading'
	);
	
	/* IMPORT/EXPORT */
	
	$sections_list[] = array(
	'id' => 'response_import_export_section',
		'label' => __('Import / Export', 'response'),
		'description' => __('Import/Export description', 'response'),
		'heading' => 'response_import_export_heading'
	);
	
	

	return $sections_list;
}
add_filter('response_section_list', 'response_add_core_sections');

// TODO: this is where we will build our default sections for the options page
function response_add_core_fields( $fields_list ) {
	
	// post byline 
	
	$pbe_defaults = array(
		'author' => 1,
		'categories' => 1,
		'date' => 1,
		'comments' => 1,
		'share' => 1,
		'tags' => 1
	);
	$pbe_array = array (
		'author' => __('Author', 'options_framework_theme'),
		'categories' => __('Categories', 'options_framework_theme'),
		'date' => __('Date', 'options_framework_theme'),
		'comments' => __('Comments', 'options_framework_theme'),
		'share' => __('Share', 'options_framework_theme'),
		'tags' => __('Tags', 'options_framework_theme')
	);
	
	
	// Pull all the categories into an array
	$options_categories = array();
	$options_categories_obj = get_categories();
	foreach ($options_categories_obj as $category) {
		$options_categories['response_all'] = 'All';
		$options_categories[$category->cat_ID] = $category->cat_name;
	}
	
	// Pull all tags into an array
	$options_tags = array();
	$options_tags_obj = get_tags();
	foreach ( $options_tags_obj as $tag ) {
		$options_tags[$tag->term_id] = $tag->name;
	}


	// Pull all the pages into an array
	$options_pages = array();
	$options_pages_obj = get_pages('sort_column=post_parent,menu_order');
	$options_pages[''] = 'Select a page:';
	foreach ($options_pages_obj as $page) {
		$options_pages[$page->ID] = $page->post_title;
	}
	
	// If using image radio buttons, define a directory path
	$imagepath =  get_template_directory_uri() . '/core/lib/images/';
	
	$fields_list = array();
	
	// Responsive Section
	$fields_list[] = array(
		'id' => 'response_responsive_design_field',
		'name' => __('Responsive Design', 'response'),
		'type' => 'toggle',
		'std' => 1,
		'section' => 'response_responsive_section',
		'heading' => 'response_design_heading',
	);
	
	$fields_list[] = array(
		'id' => 'response_responsive_videos_field',
		'name' => __('Responsive Videos', 'response'),
		'type' => 'toggle',
		'std' => 1,
		'section' => 'response_responsive_section',
		'heading' => 'response_design_heading',
	);
	
	$fields_list[] = array(
		'id' => 'response_skin_color_field',
		'name' => __('Select a Skin Color', 'response'),
		'type' => 'select',
		'std' => 'default',
		'options' => array(
			'default' => __('Default', 'response'),
			'greeb' => __('Green', 'response'),
		),
		'section' => 'response_responsive_section',
		'heading' => 'response_design_heading',
	);
	
	// Typography Defaults
	$typography_defaults = array(
		'size' => '15px',
		'face' => 'georgia',
		'style' => 'bold',
		'color' => '#bada55' );
		
	// Typography Options
	$typography_options = array(
		'sizes' => array( '6','12','14','16','20' ),
		'faces' => array( 'Helvetica Neue' => 'Helvetica Neue','Arial' => 'Arial' ),
		'styles' => array( 'normal' => 'Normal','bold' => 'Bold' ),
		'color' => false
	);
	
	// Typography Section
	$fields_list[] = array(
		'id' => 'response_typography_field',
		'name' => __('Typkit Code', 'response'),
		'desc' => __('Typekit Code description.', 'response'),
		'type' => 'typography',
		'std' => $typography_defaults,
		'options' => $typography_options,
		'section' => 'response_typography_section',
		'heading' => 'response_design_heading'
	);
	
	$fields_list[] = array(
		'id' => 'response_typekit_code_field',
		'name' => __('Typkit Code', 'response'),
		'desc' => __('Typekit Code description.', 'response'),
		'type' => 'textarea',
		'std' => '',
		'section' => 'response_typography_section',
		'heading' => 'response_design_heading'
	);
		
	/* BACKGROUND */
	
	/* TODO different themes will need different backgrounds. We need a system that can work from core and list image files to be selected */
	$fields_list[] = array(
		'name' => "Choose you background image",
		'desc' => "Images for background",
		'id' => "theme_backgrounds",
		'std' => "2c-l-fixed",
		'type' => "images",
		'options' => array(
			'1col-fixed' => $imagepath . '1col.png',
			'2c-l-fixed' => $imagepath . '2cl.png',
			'2c-r-fixed' => $imagepath . '2cr.png'),
		'section' => 'response_background_section',
		'heading' => 'response_design_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Use Custom Backgrounds', 'options_framework_theme'),
		'desc' => __('Click here to use custom backgrounds.', 'options_framework_theme'),
		'id' => 'show_custom_backgrounds',
		'type' => 'checkbox',
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	$fields_list[] = array(
		'name' => __('Colorpicker', 'options_framework_theme'),
		'desc' => __('Select background color', 'options_framework_theme'),
		'id' => 'background_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_background_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Background Image', 'options_framework_theme'),
		'desc' => __('Enter URL or upload file', 'options_framework_theme'),
		'id' => 'background_uploader',
		'type' => 'upload',
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	$alignment_array = array(
		'left' => __('Left', 'options_framework_theme'),
		'center' => __('Center', 'options_framework_theme'),
		'right' => __('Right', 'options_framework_theme')
	);	
	$fields_list[] = array(
		'name' => __('Image Position', 'options_framework_theme'),
		'desc' => __('Select the position of your image', 'options_framework_theme'),
		'id' => 'background_image_position',
		'std' => 'center',
		'type' => 'radio',
		'options' => $alignment_array,
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	$tile_array = array(
		'tile' => __('Tile', 'options_framework_theme'),
		'tile-horizontally' => __('Tile Horizontally', 'options_framework_theme'),
		'tile-vertically' => __('Tile Vertically', 'options_framework_theme'),
		'no-tile' => __('No Tile', 'options_framework_theme')
	);	
	$fields_list[] = array(
		'name' => __('Image Repeat', 'options_framework_theme'),
		'desc' => __('How do you want the image to tile?', 'options_framework_theme'),
		'id' => 'background_image_tile',
		'std' => 'tile',
		'type' => 'radio',
		'options' => $tile_array,
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	$attachment_array = array(
		'scroll' => __('Scroll', 'options_framework_theme'),
		'fixed' => __('Fixed', 'options_framework_theme')
	);	
	$fields_list[] = array(
		'name' => __('Image Scroll', 'options_framework_theme'),
		'desc' => __('Fixed or Scroll?', 'options_framework_theme'),
		'id' => 'background_image_attachment',
		'std' => 'scroll',
		'type' => 'radio',
		'options' => $attachment_array,
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
		
	/* LAYOUT */
	$fields_list[] = array(
		'name' => __('Standard Web Layout', 'options_framework_theme'),
		'desc' => __('I have no idea what this means?', 'options_framework_theme'),
		'id' => 'standard_web_layout',
		'type' => 'checkbox',
		'section' => 'response_layout_section',
		'heading' => 'response_design_heading');
		
	$fields_list[] = array(
		'name' => __('Row Max Width', 'options_framework_theme'),
		'desc' => __('Maximum width of your pages, including any sidebars', 'options_framework_theme'),
		'id' => 'row_max_width',
		'std' => '980',
		'type' => 'text',
		'section' => 'response_layout_section',
		'heading' => 'response_design_heading');
		
	$fields_list[] = array(
		'name' => __('Widget Title Background', 'options_framework_theme'),
		'desc' => __('again I have no idea what this means?', 'options_framework_theme'),
		'id' => 'widget_title_background',
		'type' => 'checkbox',
		'section' => 'response_layout_section',
		'heading' => 'response_design_heading');

	/* CUSTOMER COLORS */
	
	$fields_list[] = array(
		'name' => __('Text Color', 'options_framework_theme'),
		'desc' => __('Select text color', 'options_framework_theme'),
		'id' => 'text_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Site Title Color', 'options_framework_theme'),
		'desc' => __('Select site title color', 'options_framework_theme'),
		'id' => 'site_title_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Site Description Color', 'options_framework_theme'),
		'desc' => __('Select site description color', 'options_framework_theme'),
		'id' => 'site_description_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Link Color', 'options_framework_theme'),
		'desc' => __('Select link color', 'options_framework_theme'),
		'id' => 'link_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Link Hover Color', 'options_framework_theme'),
		'desc' => __('Select link hover color', 'options_framework_theme'),
		'id' => 'link_hover_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Post Title Color', 'options_framework_theme'),
		'desc' => __('Select post title color', 'options_framework_theme'),
		'id' => 'post_title_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Text Color', 'options_framework_theme'),
		'desc' => __('Select text color', 'options_framework_theme'),
		'id' => 'text_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );	
		
	$fields_list[] = array(
		'name' => __('Footer Color', 'options_framework_theme'),
		'desc' => __('Select footer color', 'options_framework_theme'),
		'id' => 'footer_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	/* CUSTOM CSS */
	$fields_list[] = array(
		'name' => __('Custom CSS', 'response'),
		'desc' => __('Add your custom CSS here', 'response'),
		'id' => 'custom_css',
		'type' => 'textarea',
		'std' => '',
		'section' => 'response_custom_css_section',
		'heading' => 'response_design_heading'
	);

	
	/********************************************************************/
	/* HEADER */
	/*******************************************************************/	
	
	$fields_list[] = array(
		'id' => 'response_drag_drop_field',
		'name' => __('Typkit Code', 'response'),
		'desc' => __('Typekit Code description.', 'response'),
		'callback' => 'response_drag_drop_field',
		'std' => "ifeature_header_content",
		'options' => array(
			"ifeature_header_content" => "Logo + Icons",
			"ifeature_sitename_contact" => "Logo + Contact",
			"ifeature_description_icons" => "Description + Icons",
			"ifeature_logo_menu" => "Logo + Menu",
			"ifeature_logo_Description" => "Logo + Description",
			"ifeature_banner" => "Banner",
			"ifeature_custom_header_element" => "Custom",
			"synapse_navigation" => "iMenu",
			"ifeature_sitename_register" => "Logo + Login"
		),
		'section' => 'response_header_drag_drop_section',
		'heading' => 'response_header_heading'
	);

	/********************* HEADER OPTIONS ********************************/
	
	$fields_list[] = array(
		'name' => __('Header Bar', 'options_framework_theme'),
		'desc' => __('Description for header bar', 'options_framework_theme'),
		'id' => 'header_bar',
		'type' => 'checkbox',
		'section' => 'response_header_options_section',
		'heading' => 'response_header_heading');
	
	$fields_list[] = array(
		'name' => __('Background Image', 'options_framework_theme'),
		'desc' => __('Enter URL or upload file', 'options_framework_theme'),
		'id' => 'header_background_uploader',
		'type' => 'upload',
		'section' => 'response_header_options_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Favicon', 'options_framework_theme'),
		'desc' => __('Enter URL or upload file', 'options_framework_theme'),
		'id' => 'favicon_uploader',
		'type' => 'upload',
		'section' => 'response_header_options_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Apple Touch Icon', 'options_framework_theme'),
		'desc' => __('Enter URL or upload file', 'options_framework_theme'),
		'id' => 'apple_touch_uploader',
		'type' => 'upload',
		'section' => 'response_header_options_section',
		'heading' => 'response_header_heading');
		
	/******************** iMenu Options *******************************/
	
	$fields_list[] = array(
		'name' => __('Menu Typography', 'options_framework_theme'),
		'desc' => __('Menu typography options.', 'options_framework_theme'),
		'id' => "menu_typography",
		'std' => $typography_defaults,
		'type' => 'typography',
		'options' => $typography_options,
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Colors', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'custom_menu_colors_toggle',
		'std' => '0',
		'type' => 'checkbox',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Bar Color', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'menu_bar_color_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Text Color', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'menu_text_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Dropdown Color', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'menu_dropdown_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Hover Color', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'menu_hover_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Menu Rounded Corners', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'menu_rounded_corners_toggle',
		'std' => '0',
		'type' => 'checkbox',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Home Icon', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'home_icon_toggle',
		'std' => '0',
		'type' => 'checkbox',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Searchbar', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'searchbar_toggle',
		'std' => '0',
		'type' => 'checkbox',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Mobile Searchbar', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'mobile_searchbar_toggle',
		'std' => '0',
		'type' => 'checkbox',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	/* SOCIAL */
	
	$fields_list[] = array(
		'name' => "Choose you background image",
		'desc' => "Images for background",
		'id' => "theme_backgrounds",
		'std' => "2c-l-fixed",
		'type' => "images",
		'options' => array(
			'icons-classic' => $imagepath . 'social/thumbs/icons-classic.png',
			'icons-default' => $imagepath . 'social/thumbs/icons-default.png',
			'icons-round' => $imagepath . 'social/thumbs/icons-round.png'),
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Twitter', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_twitter',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Twitter URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'twitter_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Facebook', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_facebook',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Facebook URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'facebook_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Google', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_google',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Google URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'google_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Flickr', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_flickr',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Flickr URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'flickr_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Pinterest', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_pinterest',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Pinterest URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'pinterest_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('LinkedIn', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_linkedin',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('LinkedIn URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'linkedin_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('YouTube', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_youtube',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('YouTube URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'youtube_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Google Maps', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_googlemaps',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Google Maps URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'googlemaps_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Email', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_email',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Email Address', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'email_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('RSS', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'social_rss',
		'type' => 'checkbox',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('RSS URL', 'options_framework_theme'),
		'desc' => __('Description', 'options_framework_theme'),
		'id' => 'rss_url',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	/* TRACKING AND SCRIPTS */
	
	$fields_list[] = array(
		'name' => __('Google Analytics Code', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'analytics_textarea',
		'std' => 'Default Text',
		'type' => 'textarea',
		'section' => 'response_header_scripts_section',
		'heading' => 'response_header_heading');
	
	$fields_list[] = array(
		'name' => __('Custom Header Scripts', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'custom_scripts_textarea',
		'std' => 'Default Text',
		'type' => 'textarea',
		'section' => 'response_header_scripts_section',
		'heading' => 'response_header_heading');
		
	/**************************************************************************/
	/* BLOG */
	/**************************************************************************/
	
	$fields_list[] = array(
		'id' => 'response_blog_drag_drop_field',
		'name' => __('Drag & Drop Blog Elements', 'response'),
		'desc' => __('description.', 'response'),
		'callback' => 'response_drag_drop_field',
		'std' => "blog_post_page",
		'options' => array(
			"blog_post_page" => "Post Page",
			"response_slider" => "Slider",
			"callout_section" => "Callout Section",
			"twitter_bar" => "Twitter Bar",
			"carousel" => "Carousel",
			"portfolio" => "Portfolio",
			"product" => "Product",
			"boxes" => "Boxes"
		),
		'section' => 'response_blog_drag_and_drop_section',
		'heading' => 'response_blog_heading'
	);
	
	/********* BLOG OPTIONS *******************/
	
	$fields_list[] = array(
		'name' => "Sidebar Options",
		'desc' => "description",
		'id' => "sidebar_images",
		'std' => "2c-l-fixed",
		'type' => "images",
		'options' => array(
			'1col-fixed' => $imagepath . '1col.png',
			'2c-l-fixed' => $imagepath . '2cl.png',
			'2c-r-fixed' => $imagepath . '2cr.png'),
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Formats Icons', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'post_format_icons',
		'type' => 'checkbox',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
	
	$fields_list[] = array(
		'name' => __('Post Excerpts', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'post_excerpts',
		'type' => 'checkbox',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
		
	$fields_list[] = array(
		'name' => __('Featured Images', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'post_featured_images',
		'type' => 'checkbox',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
	
	$fields_list[] = array(
		'name' => __('Post Byline Elements', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'post_byline_elements',
		'std' => $pbe_defaults, // These items get checked by default
		'type' => 'multicheck',
		'options' => $pbe_array,
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
		
	$fields_list[] = array(
		'name' => __('Facebook Like Button', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'facebook_like',
		'type' => 'checkbox',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
		
	$fields_list[] = array(
		'name' => __('Google Plus One Button', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'google_plus_one',
		'type' => 'checkbox',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
		
	/*********** BLOG SLIDER ******************************/
	
	$fields_list[] = array(
		'name' => __('Slider Size', 'response'),
		'id' => 'blog_slider_size',
		'type' => 'select',
		'std' => 'full',
		'options' => array(
			'full' => __('Full', 'response'),
			'half' => __('Half', 'response'),
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Type', 'response'),
		'id' => 'blog_slider_type',
		'type' => 'select',
		'std' => 'posts',
		'options' => array(
			'posts' => __('Posts', 'response'),
			'custom' => __('Custom', 'response'),
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Post Categories', 'response'),
		'id' => 'blog_slider_post_cats',
		'type' => 'select',
		'std' => 'response_all',
		'options' => $options_categories,
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Number of Featured Blog Posts', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'blog_no_featured_posts',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Height', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'blog_slider_height',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Animation', 'response'),
		'id' => 'blog_slider_animation',
		'type' => 'select',
		'std' => 'horizontal-push',
		'options' => array(
			'horizontal-push' => __('Horizontal Push', 'response'),
			'fade' => __('Fade', 'response'),
			'horizontal-slide' => __('Horizontal Slide', 'response'),
			'vertical-slide' => __('Vertical Slide', 'reponse')
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Caption Style', 'response'),
		'id' => 'blog_slider_caption_style',
		'type' => 'select',
		'std' => 'bottom',
		'options' => array(
			'bottom' => __('Bottom', 'response'),
			'right' => __('Right', 'response'),
			'left' => __('Left', 'response'),
			'none' => __('None', 'reponse')
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Caption Animation', 'response'),
		'id' => 'blog_caption_animation',
		'type' => 'select',
		'std' => 'fade',
		'options' => array(
			'fade' => __('Fade', 'response'),
			'slide-open' => __('Slide Open', 'response'),
			'none' => __('None', 'response')
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Navigation', 'response'),
		'id' => 'blog_slider_navigation',
		'type' => 'select',
		'std' => 'dots',
		'options' => array(
			'dots' => __('Dots', 'response'),
			'thumbs' => __('Thumbnails', 'response'),
			'none' => __('None', 'response')
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Arrows', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'blog_slider_arrows',
		'type' => 'checkbox',
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Word Thumb Image Resizing', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'blog_word_image_resizing',
		'type' => 'checkbox',
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading'
	);
	
	/*********** SEO *****************/
	
	$fields_list[] = array(
		'name' => __('Home Description', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'seo_home_desc',
		'std' => 'Default Text',
		'type' => 'textarea',
		'section' => 'response_blog_seo_section',
		'heading' => 'response_blog_heading');	
		
	$fields_list[] = array(
		'name' => __('Home Keywords', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'seo_home_keywords',
		'std' => 'Default Text',
		'type' => 'textarea',
		'section' => 'response_blog_seo_section',
		'heading' => 'response_blog_heading');	
		
	$fields_list[] = array(
		'name' => __('Optional Home Title', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'seo_optional_title',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_blog_seo_section',
		'heading' => 'response_blog_heading',
	);
	
	/*************************************************************/
	/* TEMPLATES */
	/*************************************************************/
	
	/* SINGLE POSTS */
	
	$fields_list[] = array(
		'name' => "Sidebar Options",
		'desc' => "Images for layout.",
		'id' => "single_post_sidebar_options",
		'std' => "2c-l-fixed",
		'type' => "images",
		'options' => array(
			'1col-fixed' => $imagepath . '1col.png',
			'2c-l-fixed' => $imagepath . '2cl.png',
			'2c-r-fixed' => $imagepath . '2cr.png'),
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Breadcrumbs', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'single_post_breadcrumbs',
		'type' => 'checkbox',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Featured Images', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'single_post_featured_images',
		'type' => 'checkbox',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Format Icons', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'single_post_format_icons',
		'type' => 'checkbox',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Byline Elements', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'single_post_byline_elements',
		'std' => $pbe_defaults, // These items get checked by default
		'type' => 'multicheck',
		'options' => $pbe_array,
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
		);

	$fields_list[] = array(
		'name' => __('Facebook Like Button', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'single_post_facebook_like',
		'type' => 'checkbox',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Google Plus One Button', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'single_post_google_plus',
		'type' => 'checkbox',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Pagination Links', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'single_post_post_pagination',
		'type' => 'checkbox',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	/* ARCHIVE */
	
	$fields_list[] = array(
		'name' => "Sidebar Options",
		'desc' => "Images for layout.",
		'id' => "archive_sidebar_options",
		'std' => "2c-l-fixed",
		'type' => "images",
		'options' => array(
			'1col-fixed' => $imagepath . '1col.png',
			'2c-l-fixed' => $imagepath . '2cl.png',
			'2c-r-fixed' => $imagepath . '2cr.png'),
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Breadcrumbs', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'archive_breadcrumbs',
		'type' => 'checkbox',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Featured Images', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'archive_featured_images',
		'type' => 'checkbox',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Format Icons', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'archive_format_icons',
		'type' => 'checkbox',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Byline Elements', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'archive_post_byline_elements',
		'std' => $pbe_defaults, // These items get checked by default
		'type' => 'multicheck',
		'options' => $pbe_array,
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
		);

	$fields_list[] = array(
		'name' => __('Facebook Like Button', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'archive_facebook_like',
		'type' => 'checkbox',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Google Plus One Button', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'archive_google_plus',
		'type' => 'checkbox',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	/*SEARCH */
	
	$fields_list[] = array(
		'name' => "Sidebar Options",
		'desc' => "Images for layout.",
		'id' => "search_sidebar_options",
		'std' => "2c-l-fixed",
		'type' => "images",
		'options' => array(
			'1col-fixed' => $imagepath . '1col.png',
			'2c-l-fixed' => $imagepath . '2cl.png',
			'2c-r-fixed' => $imagepath . '2cr.png'),
		'section' => 'response_search_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Excerpts', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'search_post_excerpts',
		'type' => 'checkbox',
		'section' => 'response_search_section',
		'heading' => 'response_templates_heading'
	);
	
	/*404 */
	
	$fields_list[] = array(
		'name' => "Sidebar Options",
		'desc' => "Images for layout.",
		'id' => "error_sidebar_options",
		'std' => "2c-l-fixed",
		'type' => "images",
		'options' => array(
			'1col-fixed' => $imagepath . '1col.png',
			'2c-l-fixed' => $imagepath . '2cl.png',
			'2c-r-fixed' => $imagepath . '2cr.png'),
		'section' => 'response_error_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Custom 404 Content', 'options_framework_theme'),
		'desc' => __('Custom 404 description.', 'options_framework_theme'),
		'id' => 'example_textarea',
		'std' => 'Default Text',
		'type' => 'textarea',
		'section' => 'response_error_section',
		'heading' => 'response_templates_heading'
	);
	
	/************************************************************************************/
	/* FOOTER */
	/************************************************************************************/
	
	$fields_list[] = array(
		'name' => __('Footer', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'footer_toggle',
		'type' => 'checkbox',
		'section' => 'response_footer_section',
		'heading' => 'response_footer_heading'
	);
	
	$fields_list[] = array(
		'id' => 'footer_copyright_text',
		'name' => __('Footer Copyright Text', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_footer_section',
		'heading' => 'response_footer_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Cyberchimps Link', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'footer_cyberchimps_link',
		'type' => 'checkbox',
		'section' => 'response_footer_section',
		'heading' => 'response_footer_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Afterfooter', 'options_framework_theme'),
		'desc' => __('description', 'options_framework_theme'),
		'id' => 'afterfooter_toggle',
		'type' => 'checkbox',
		'section' => 'response_footer_section',
		'heading' => 'response_footer_heading'
	);
	
	/****************************************************************/
	/* IMPORT EXPORT */
	/***************************************************************/
	
	$fields_list[] = array(
		'name' => __('Export Settings', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'export_textarea',
		'std' => 'Default Text',
		'type' => 'textarea',
		'section' => 'response_import_export_section',
		'heading' => 'response_import_export_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Import Settings', 'options_framework_theme'),
		'desc' => __('description.', 'options_framework_theme'),
		'id' => 'import_textarea',
		'std' => 'Default Text',
		'type' => 'textarea',
		'section' => 'response_import_export_section',
		'heading' => 'response_import_export_heading'
	);
	
	
	
	
	
	
	
	
	
		
		
		
	
	
	/* Fields for Reference Remove Once Fields are Finished */
	// Test data
	$test_array = array(
		'one' => __('One', 'options_framework_theme'),
		'two' => __('Two', 'options_framework_theme'),
		'three' => __('Three', 'options_framework_theme'),
		'four' => __('Four', 'options_framework_theme'),
		'five' => __('Five', 'options_framework_theme')
	);

	// Multicheck Array
	$multicheck_array = array(
		'one' => __('French Toast', 'options_framework_theme'),
		'two' => __('Pancake', 'options_framework_theme'),
		'three' => __('Omelette', 'options_framework_theme'),
		'four' => __('Crepe', 'options_framework_theme'),
		'five' => __('Waffle', 'options_framework_theme')
	);

	// Multicheck Defaults
	$multicheck_defaults = array(
		'one' => '1',
		'five' => '1'
	);

	// Background Defaults
	$background_defaults = array(
		'color' => '',
		'image' => '',
		'repeat' => 'repeat',
		'position' => 'top center',
		'attachment'=>'scroll' );
	
	$fields_list[] = array(
		'id' => 'response_skin_color_field',
		'name' => __('Select a Skin Color', 'response'),
		'type' => 'select',
		'std' => 'default',
		'options' => array(
			'default' => __('Default', 'response'),
			'greeb' => __('Green', 'response'),
		),
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading',
	);
	
	$fields_list[] = array(
		'id' => 'core_text',
		'name' => __('Input Text', 'options_framework_theme'),
		'desc' => __('A text input field.', 'options_framework_theme'),
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading', // TODO: try to remove and have add_settings_field pull from get_sections()
	);
	
	$fields_list[] = array(
		'name' => __('Input Text Mini', 'options_framework_theme'),
		'desc' => __('A mini text input field.', 'options_framework_theme'),
		'id' => 'example_text_mini',
		'std' => 'Default',
		'class' => 'input-mini',
		'type' => 'text',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Input Text', 'options_framework_theme'),
		'desc' => __('A text input field.', 'options_framework_theme'),
		'id' => 'example_text',
		'std' => 'Default Value',
		'type' => 'text',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Textarea', 'options_framework_theme'),
		'desc' => __('Textarea description.', 'options_framework_theme'),
		'id' => 'example_textarea',
		'std' => 'Default Text',
		'type' => 'textarea',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Input Select Small', 'options_framework_theme'),
		'desc' => __('Small Select Box.', 'options_framework_theme'),
		'id' => 'example_select',
		'std' => 'three',
		'type' => 'select',
		'class' => 'select-mini', //mini, tiny, small
		'options' => $test_array,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Input Select Wide', 'options_framework_theme'),
		'desc' => __('A wider select box.', 'options_framework_theme'),
		'id' => 'example_select_wide',
		'std' => 'two',
		'type' => 'select',
		'options' => $test_array,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Select a Category', 'options_framework_theme'),
		'desc' => __('Passed an array of categories with cat_ID and cat_name', 'options_framework_theme'),
		'id' => 'example_select_categories',
		'type' => 'select',
		'options' => $options_categories,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');
		
	$fields_list[] = array(
		'name' => __('Select a Tag', 'options_check'),
		'desc' => __('Passed an array of tags with term_id and term_name', 'options_check'),
		'id' => 'example_select_tags',
		'type' => 'select',
		'options' => $options_tags,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Select a Page', 'options_framework_theme'),
		'desc' => __('Passed an pages with ID and post_title', 'options_framework_theme'),
		'id' => 'example_select_pages',
		'type' => 'select',
		'options' => $options_pages,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Input Radio (one)', 'options_framework_theme'),
		'desc' => __('Radio select with default options "one".', 'options_framework_theme'),
		'id' => 'example_radio',
		'std' => 'one',
		'type' => 'radio',
		'options' => $test_array,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Example Info', 'options_framework_theme'),
		'desc' => __('This is just some example information you can put in the panel.', 'options_framework_theme'),
		'type' => 'info',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Input Checkbox', 'options_framework_theme'),
		'desc' => __('Example checkbox, defaults to true.', 'options_framework_theme'),
		'id' => 'example_checkbox',
		'std' => '1',
		'type' => 'checkbox',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Check to Show a Hidden Text Input', 'options_framework_theme'),
		'desc' => __('Click here and see what happens.', 'options_framework_theme'),
		'id' => 'example_showhidden',
		'type' => 'checkbox',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');
		
	$fields_list[] = array(
		'name' => __('Hidden Text Input', 'options_framework_theme'),
		'desc' => __('This option is hidden unless activated by a checkbox click.', 'options_framework_theme'),
		'id' => 'example_text_hidden',
		'std' => 'Hello',
		'class' => 'hidden',
		'type' => 'text',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Uploader Test', 'options_framework_theme'),
		'desc' => __('This creates a full size uploader that previews the image.', 'options_framework_theme'),
		'id' => 'example_uploader',
		'type' => 'upload',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => "Example Image Selector",
		'desc' => "Images for layout.",
		'id' => "example_images",
		'std' => "2c-l-fixed",
		'type' => "images",
		'options' => array(
			'1col-fixed' => $imagepath . '1col.png',
			'2c-l-fixed' => $imagepath . '2cl.png',
			'2c-r-fixed' => $imagepath . '2cr.png'),
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading'
	);

	$fields_list[] = array(
		'name' =>  __('Example Background', 'options_framework_theme'),
		'desc' => __('Change the background CSS.', 'options_framework_theme'),
		'id' => 'example_background',
		'std' => $background_defaults,
		'type' => 'background',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading' );

	$fields_list[] = array(
		'name' => __('Multicheck', 'options_framework_theme'),
		'desc' => __('Multicheck description.', 'options_framework_theme'),
		'id' => 'example_multicheck',
		'std' => $multicheck_defaults, // These items get checked by default
		'type' => 'multicheck',
		'options' => $multicheck_array,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	$fields_list[] = array(
		'name' => __('Colorpicker', 'options_framework_theme'),
		'desc' => __('No color selected by default.', 'options_framework_theme'),
		'id' => 'example_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array( 'name' => __('Typography', 'options_framework_theme'),
		'desc' => __('Example typography.', 'options_framework_theme'),
		'id' => "example_typography",
		'std' => $typography_defaults,
		'type' => 'typography',
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Custom Typography', 'options_framework_theme'),
		'desc' => __('Custom typography options.', 'options_framework_theme'),
		'id' => "custom_typography",
		'std' => $typography_defaults,
		'type' => 'typography',
		'options' => $typography_options,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading');

	/**
	 * For $settings options see:
	 * http://codex.wordpress.org/Function_Reference/wp_editor
	 *
	 * 'media_buttons' are not supported as there is no post to attach items to
	 * 'textarea_name' is set by the 'id' you choose
		 */

	$wp_editor_settings = array(
		'wpautop' => true, // Default
		'textarea_rows' => 5,
		'tinymce' => array( 'plugins' => 'wordpress' )
	);
	
	$fields_list[] = array(
		'name' => __('Default Text Editor', 'options_framework_theme'),
		'desc' => sprintf( __( 'You can also pass settings to the editor.  Read more about wp_editor in <a href="%1$s" target="_blank">the WordPress codex</a>', 'options_framework_theme' ), 'http://codex.wordpress.org/Function_Reference/wp_editor' ),
		'id' => 'example_editor',
		'type' => 'editor',
		'settings' => $wp_editor_settings,
		'section' => 'response_temp_styling_section',
		'heading' => 'response_design_heading' );
	
	return $fields_list;
}
add_filter('response_field_list', 'response_add_core_fields');