<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

function response_add_core_headings( $headings_list ) {
	
	$headings_list = array();
	
	$headings_list[] = array(
		'id' => 'response_welcome_heading',
		'title' => __('Welcome', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_design_heading',
		'title' => __('Design', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_header_heading',
		'title' => __('Header', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_blog_heading',
		'title' => __('Blog', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_templates_heading',
		'title' => __('Templates', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_footer_heading',
		'title' => __('Footer', 'response'),
	);
	
	$headings_list[] = array(
		'id' => 'response_import_export_heading',
		'title' => __('Import/Export', 'response'),
	);
	
	return $headings_list;
}
add_filter('response_heading_list', 'response_add_core_headings');

function response_add_core_sections( $sections_list ) {
	
	$sections_list = array();
	
	$sections_list[] = array(
		'id' => 'response_responsive_section',
		'label' => __('Responsive', 'response'),
		'heading' => 'response_design_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_typography_section',
		'label' => __('Typography', 'response'),
		'heading' => 'response_design_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_background_section',
		'label' => __('Background', 'response'),
		'heading' => 'response_design_heading'
	);
	
	/* TODO: Decide to remove
	$sections_list[] = array(
		'id' => 'response_layout_section',
		'label' => __('Layout', 'response'),
		'heading' => 'response_design_heading'
	);
	*/
	
	$sections_list[] = array(
		'id' => 'response_custom_colors_section',
		'label' => __('Custom Colors', 'response'),
		'heading' => 'response_design_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_custom_css_section',
		'label' => __('Custom CSS', 'response'),
		'description' => __('Custom CSS Description', 'response'),
		'heading' => 'response_design_heading'
	);
	
	/* HEADER */
	$sections_list[] = array(
		'id' => 'response_header_drag_drop_section',
		'label' => __('Header Drag/Drop', 'response'),
		'heading' => 'response_header_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_header_options_section',
		'label' => __('Header Options', 'response'),
		'heading' => 'response_header_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_header_imenu_section',
		'label' => __('iMenu Options', 'response'),
		'heading' => 'response_header_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_header_social_section',
		'label' => __('Social', 'response'),
		'heading' => 'response_header_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_header_scripts_section',
		'label' => __('Tracking and Scripts', 'response'),
		'heading' => 'response_header_heading'
	);
	
	/* BLOG */
	$sections_list[] = array(
		'id' => 'response_blog_drag_and_drop_section',
		'label' => __('Drag & Drop', 'response'),
		'heading' => 'response_blog_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_blog_options_section',
		'label' => __('Blog Options', 'response'),
		'heading' => 'response_blog_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_blog_slider_section',
		'label' => __('Blog Slider', 'response'),
		'heading' => 'response_blog_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_blog_seo_section',
		'label' => __('SEO', 'response'),
		'heading' => 'response_blog_heading'
	);
	
	/* TEMPLATE */
	$sections_list[] = array(
		'id' => 'response_single_post_section',
		'label' => __('Single Post', 'response'),
		'heading' => 'response_templates_heading'
	);
		
	$sections_list[] = array(
		'id' => 'response_archive_section',
		'label' => __('Archive', 'response'),
		'heading' => 'response_templates_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_search_section',
		'label' => __('Search', 'response'),
		'heading' => 'response_templates_heading'
	);
	
	$sections_list[] = array(
		'id' => 'response_error_section',
		'label' => __('404', 'response'),
		'heading' => 'response_templates_heading'
	);
	
	/* FOOTER */
	$sections_list[] = array(
		'id' => 'response_footer_section',
		'label' => __('Footer Options', 'response'),
		'heading' => 'response_footer_heading'
	);
	
	/* IMPORT/EXPORT */
	$sections_list[] = array(
		'id' => 'response_import_export_section',
		'label' => __('Import / Export', 'response'),
		'heading' => 'response_import_export_heading'
	);

	return $sections_list;
}
add_filter('response_section_list', 'response_add_core_sections');

function response_add_core_fields( $fields_list ) {
	
	// post byline 
	$pbe_defaults = array(
		'author' => 1,
		'categories' => 1,
		'date' => 1,
		'comments' => 1,
		'share' => 1,
		'tags' => 1
	);
	$pbe_array = array (
		'author' => __('Author', 'response'),
		'categories' => __('Categories', 'response'),
		'date' => __('Date', 'response'),
		'comments' => __('Comments', 'response'),
		'share' => __('Share', 'response'),
		'tags' => __('Tags', 'response')
	);
	
	
	// Pull all the categories into an array
	$options_categories = array();
	$options_categories_obj = get_categories();
	foreach ($options_categories_obj as $category) {
		$options_categories['response_all'] = 'All';
		$options_categories[$category->cat_ID] = $category->cat_name;
	}
	
	// Pull all tags into an array
	$options_tags = array();
	$options_tags_obj = get_tags();
	foreach ( $options_tags_obj as $tag ) {
		$options_tags[$tag->term_id] = $tag->name;
	}


	// Pull all the pages into an array
	$options_pages = array();
	$options_pages_obj = get_pages('sort_column=post_parent,menu_order');
	$options_pages[''] = 'Select a page:';
	foreach ($options_pages_obj as $page) {
		$options_pages[$page->ID] = $page->post_title;
	}
	
	// If using image radio buttons, define a directory path
	$imagepath =  get_template_directory_uri() . '/core/lib/images/';
	
	$fields_list = array();
	
	// Responsive Section
	$fields_list[] = array(
		'id' => 'responsive_design',
		'name' => __('Responsive Design', 'response'),
		'type' => 'toggle',
		'std' => 1,
		'section' => 'response_responsive_section',
		'heading' => 'response_design_heading',
	);
	
	$fields_list[] = array(
		'id' => 'responsive_videos',
		'name' => __('Responsive Videos', 'response'),
		'type' => 'toggle',
		'std' => 1,
		'section' => 'response_responsive_section',
		'heading' => 'response_design_heading',
	);
	
	$fields_list[] = array(
		'id' => 'skin_color',
		'name' => __('Select a Skin Color', 'response'),
		'type' => 'select',
		'std' => 'blue',
		'options' => array(
			'default' => __('Default', 'response'),
			'blue' => __('Blue', 'response'),
			'green' => __('Green', 'response'),
		),
		'section' => 'response_responsive_section',
		'heading' => 'response_design_heading',
	);
	
	// Typography Defaults
	$typography_defaults = array(
		'size' => '15px',
		'face' => 'georgia',
		'style' => 'bold',
		'color' => '#bada55' );
		
	// Typography Options
	$typography_options = array(
		'sizes' => array( '6','12','14','16','20' ),
		'faces' => array( 'Helvetica Neue' => 'Helvetica Neue','Arial' => 'Arial' ),
		'styles' => array( 'normal' => 'Normal','bold' => 'Bold' ),
		'color' => false
	);
	
	// Typography Section
	$fields_list[] = array(
		'id' => 'typography_options',
		'name' => __('Typkit Options', 'response'),
		'type' => 'typography',
		'std' => $typography_defaults,
		'options' => $typography_options,
		'section' => 'response_typography_section',
		'heading' => 'response_design_heading'
	);
	
	$fields_list[] = array(
		'id' => 'typekit_code',
		'name' => __('Typkit Code', 'response'),
		'type' => 'textarea',
		'std' => '',
		'section' => 'response_typography_section',
		'heading' => 'response_design_heading'
	);
		
	/* BACKGROUND */
	
	/* TODO different themes will need different backgrounds. We need a system that can work from core and list image files to be selected */
	$fields_list[] = array(
		'name' => __('Choose you background image', 'response'),
		'desc' => __('Images for background', 'response'),
		'id' => 'theme_backgrounds',
		'std' => 'right_sidebar',
		'type' => 'images',
		'options' => array(
			'full_width' => $imagepath . '1col.png',
			'right_sidebar' => $imagepath . '2cr.png',
			'left_sidebar' => $imagepath . '2cl.png',
		),
		'section' => 'response_background_section',
		'heading' => 'response_design_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Use Custom Backgrounds', 'response'),
		'desc' => __('Click here to use custom backgrounds.', 'response'),
		'id' => 'show_custom_backgrounds',
		'type' => 'toggle',
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	$fields_list[] = array(
		'name' => __('Colorpicker', 'response'),
		'desc' => __('Select background color', 'response'),
		'id' => 'background_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_background_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Background Image', 'response'),
		'desc' => __('Enter URL or upload file', 'response'),
		'id' => 'background_uploader',
		'type' => 'upload',
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	$alignment_array = array(
		'left' => __('Left', 'response'),
		'center' => __('Center', 'response'),
		'right' => __('Right', 'response')
	);	
	$fields_list[] = array(
		'name' => __('Image Position', 'response'),
		'desc' => __('Select the position of your image', 'response'),
		'id' => 'background_image_position',
		'std' => 'center',
		'type' => 'radio',
		'options' => $alignment_array,
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	$tile_array = array(
		'tile' => __('Tile', 'response'),
		'tile-horizontally' => __('Tile Horizontally', 'response'),
		'tile-vertically' => __('Tile Vertically', 'response'),
		'no-tile' => __('No Tile', 'response')
	);	
	$fields_list[] = array(
		'name' => __('Image Repeat', 'response'),
		'desc' => __('How do you want the image to tile?', 'response'),
		'id' => 'background_image_tile',
		'std' => 'tile',
		'type' => 'radio',
		'options' => $tile_array,
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	$attachment_array = array(
		'scroll' => __('Scroll', 'response'),
		'fixed' => __('Fixed', 'response')
	);	
	$fields_list[] = array(
		'name' => __('Image Scroll', 'response'),
		'desc' => __('Fixed or Scroll?', 'response'),
		'id' => 'background_image_attachment',
		'std' => 'scroll',
		'type' => 'radio',
		'options' => $attachment_array,
		'section' => 'response_background_section',
		'heading' => 'response_design_heading');
		
	/* LAYOUT */
	/* TODO: Clean Up
	$fields_list[] = array(
		'name' => __('Standard Web Layout', 'response'),
		'desc' => __('I have no idea what this means?', 'response'),
		'id' => 'standard_web_layout',
		'type' => 'checkbox',
		'section' => 'response_layout_section',
		'heading' => 'response_design_heading');
	*/
	
	/* TODO: Decide to remove	
	$fields_list[] = array(
		'name' => __('Row Max Width', 'response'),
		'desc' => __('Maximum width of your pages, including any sidebars', 'response'),
		'id' => 'row_max_width',
		'std' => '980',
		'type' => 'text',
		'section' => 'response_layout_section',
		'heading' => 'response_design_heading');
	*/
	
	/* TODO: Clean Up	
	$fields_list[] = array(
		'name' => __('Widget Title Background', 'response'),
		'id' => 'widget_title_background',
		'type' => 'checkbox',
		'section' => 'response_layout_section',
		'heading' => 'response_design_heading');
	*/
	
	/* CUSTOMER COLORS */
	
	$fields_list[] = array(
		'name' => __('Text Color', 'response'),
		'desc' => __('Select text color', 'response'),
		'id' => 'text_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Site Title Color', 'response'),
		'desc' => __('Select site title color', 'response'),
		'id' => 'site_title_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Site Description Color', 'response'),
		'desc' => __('Select site description color', 'response'),
		'id' => 'site_description_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Link Color', 'response'),
		'desc' => __('Select link color', 'response'),
		'id' => 'link_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Link Hover Color', 'response'),
		'desc' => __('Select link hover color', 'response'),
		'id' => 'link_hover_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Post Title Color', 'response'),
		'desc' => __('Select post title color', 'response'),
		'id' => 'post_title_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	$fields_list[] = array(
		'name' => __('Text Color', 'response'),
		'desc' => __('Select text color', 'response'),
		'id' => 'text_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );	
		
	$fields_list[] = array(
		'name' => __('Footer Color', 'response'),
		'desc' => __('Select footer color', 'response'),
		'id' => 'footer_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_custom_colors_section',
		'heading' => 'response_design_heading' );
		
	/* CUSTOM CSS */
	$fields_list[] = array(
		'name' => __('Custom CSS', 'response'),
		'desc' => __('Add your custom CSS here', 'response'),
		'id' => 'custom_css',
		'type' => 'textarea',
		'std' => '',
		'section' => 'response_custom_css_section',
		'heading' => 'response_design_heading'
	);

	
	/********************************************************************/
	/* HEADER */
	/*******************************************************************/	
	
	$fields_list[] = array(
		'id' => 'header_section_order',
		'name' => __('Header Drag/Drop', 'response'),
		'callback' => 'response_drag_drop_field',
		'std' => array(
			"response_header_content" => "Logo + Icons",
		),
		'type' => 'section_order',
		'options' => array(
			"response_header_content" => "Logo + Icons",
			"response_sitename_contact" => "Logo + Contact",
			"response_description_icons" => "Description + Icons",
			"response_logo_menu" => "Logo + Menu",
			"response_logo_Description" => "Logo + Description",
			"response_banner" => "Banner",
			"response_custom_header_element" => "Custom",
			"response_navigation" => "iMenu",
			"response_sitename_register" => "Logo + Login"
		),
		'section' => 'response_header_drag_drop_section',
		'heading' => 'response_header_heading'
	);

	/********************* HEADER OPTIONS ********************************/

	$fields_list[] = array(
		'name' => __('Custom Logo', 'response'),
		'id' => 'custom_logo_display',
		'type' => 'toggle',
		'section' => 'response_header_options_section',
		'heading' => 'response_header_heading');
	
	$fields_list[] = array(
		'name' => __('Logo Image', 'response'),
		'desc' => __('Enter URL or upload file', 'response'),
		'id' => 'custom_logo',
		'type' => 'upload',
		'std' => get_template_directory_uri() . '/core/lib/images/responselogo.png',
		'section' => 'response_header_options_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Favicon', 'response'),
		'desc' => __('Enter URL or upload file', 'response'),
		'id' => 'favicon_uploader',
		'type' => 'upload',
		'section' => 'response_header_options_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Apple Touch Icon', 'response'),
		'desc' => __('Enter URL or upload file', 'response'),
		'id' => 'apple_touch_uploader',
		'type' => 'upload',
		'section' => 'response_header_options_section',
		'heading' => 'response_header_heading');
		
	/******************** iMenu Options *******************************/
	
	$fields_list[] = array(
		'name' => __('Menu Typography', 'response'),
		'id' => 'menu_typography',
		'std' => $typography_defaults,
		'type' => 'typography',
		'options' => $typography_options,
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Colors', 'response'),
		'id' => 'custom_menu_colors_toggle',
		'type' => 'toggle',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Bar Color', 'response'),
		'id' => 'menu_bar_color_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Text Color', 'response'),
		'id' => 'menu_text_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Dropdown Color', 'response'),
		'id' => 'menu_dropdown_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Custom Menu Hover Color', 'response'),
		'id' => 'menu_hover_colorpicker',
		'std' => '',
		'type' => 'color',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Menu Rounded Corners', 'response'),
		'id' => 'menu_rounded_corners_toggle',
		'type' => 'toggle',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Home Icon', 'response'),
		'id' => 'home_icon_toggle',
		'type' => 'toggle',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Searchbar', 'response'),
		'id' => 'searchbar_toggle',
		'type' => 'toggle',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Mobile Searchbar', 'response'),
		'id' => 'mobile_searchbar_toggle',
		'type' => 'toggle',
		'section' => 'response_header_imenu_section',
		'heading' => 'response_header_heading');
		
	/* SOCIAL */
	
	$fields_list[] = array(
		'name' => __('Choose you background image', 'response'),
		'desc' => __('Images for background', 'response'),
		'id' => 'theme_backgrounds',
		'std' => 'default',
		'type' => 'images',
		'options' => array(
			'classic' => $imagepath . 'social/thumbs/icons-classic.png',
			'default' => $imagepath . 'social/thumbs/icons-default.png',
			'round' => $imagepath . 'social/thumbs/icons-round.png'),
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Twitter', 'response'),
		'id' => 'social_twitter',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Twitter URL', 'response'),
		'id' => 'twitter_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Facebook', 'response'),
		'id' => 'social_facebook',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Facebook URL', 'response'),
		'id' => 'facebook_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Google', 'response'),
		'id' => 'social_google',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Google URL', 'response'),
		'id' => 'google_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Flickr', 'response'),
		'id' => 'social_flickr',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Flickr URL', 'response'),
		'id' => 'flickr_url',
		'std' => 'http://www.flickr.com/',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Pinterest', 'response'),
		'id' => 'social_pinterest',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Pinterest URL', 'response'),
		'id' => 'pinterest_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('LinkedIn', 'response'),
		'id' => 'social_linkedin',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('LinkedIn URL', 'response'),
		'id' => 'linkedin_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('YouTube', 'response'),
		'id' => 'social_youtube',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('YouTube URL', 'response'),
		'id' => 'youtube_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Google Maps', 'response'),
		'id' => 'social_googlemaps',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Google Maps URL', 'response'),
		'id' => 'googlemaps_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Email', 'response'),
		'id' => 'social_email',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('Email Address', 'response'),
		'id' => 'email_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	$fields_list[] = array(
		'name' => __('RSS', 'response'),
		'id' => 'social_rss',
		'type' => 'toggle',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading');
		
	$fields_list[] = array(
		'name' => __('RSS URL', 'response'),
		'id' => 'rss_url',
		'std' => 'http://',
		'type' => 'text',
		'section' => 'response_header_social_section',
		'heading' => 'response_header_heading'
	);
	
	/* TRACKING AND SCRIPTS */
	$fields_list[] = array(
		'name' => __('Google Analytics Code', 'response'),
		'id' => 'analytics_textarea',
		'std' => '',
		'type' => 'textarea',
		'section' => 'response_header_scripts_section',
		'heading' => 'response_header_heading');
	
	$fields_list[] = array(
		'name' => __('Custom Header Scripts', 'response'),
		'id' => 'custom_scripts_textarea',
		'std' => '',
		'type' => 'textarea',
		'section' => 'response_header_scripts_section',
		'heading' => 'response_header_heading');
		
	/**************************************************************************/
	/* BLOG */
	/**************************************************************************/
	
	$fields_list[] = array(
		'id' => 'blog_section_order',
		'name' => __('Drag & Drop Blog Elements', 'response'),
		'callback' => 'response_drag_drop_field',
		'std' => array(
			"blog_post_page" => "Post Page",
		),
		'type' => 'section_order',
		'options' => array(
			"blog_post_page" => "Post Page",
			"response_slider" => "Slider",
			"callout_section" => "Callout Section",
			"twitter_bar" => "Twitter Bar",
			"carousel" => "Carousel",
			"portfolio" => "Portfolio",
			"product" => "Product",
			"boxes" => "Boxes"
		),
		'section' => 'response_blog_drag_and_drop_section',
		'heading' => 'response_blog_heading'
	);
	
	/********* BLOG OPTIONS *******************/
	
	$fields_list[] = array(
		'name' => __('Sidebar Options', 'response'),
		'id' => 'sidebar_images',
		'std' => 'right_sidebar',
		'type' => 'images',
		'options' => array(
			'full_width' => $imagepath . '1col.png',
			'right_sidebar' => $imagepath . '2cr.png',
			'left_sidebar' => $imagepath . '2cl.png',
		),
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Formats Icons', 'response'),
		'id' => 'post_format_icons',
		'type' => 'toggle',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
	
	$fields_list[] = array(
		'name' => __('Post Excerpts', 'response'),
		'id' => 'post_excerpts',
		'type' => 'toggle',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
		
	$fields_list[] = array(
		'name' => __('Featured Images', 'response'),
		'id' => 'post_featured_images',
		'type' => 'toggle',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
	
	$fields_list[] = array(
		'name' => __('Post Byline Elements', 'response'),
		'id' => 'post_byline_elements',
		'std' => $pbe_defaults, // These items get checked by default
		'type' => 'multicheck',
		'options' => $pbe_array,
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
		
	$fields_list[] = array(
		'name' => __('Facebook Like Button', 'response'),
		'id' => 'facebook_like',
		'type' => 'toggle',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
		
	$fields_list[] = array(
		'name' => __('Google Plus One Button', 'response'),
		'id' => 'google_plus_one',
		'type' => 'toggle',
		'section' => 'response_blog_options_section',
		'heading' => 'response_blog_heading');
		
	/*********** BLOG SLIDER ******************************/
	
	$fields_list[] = array(
		'name' => __('Slider Size', 'response'),
		'id' => 'blog_slider_size',
		'type' => 'select',
		'std' => 'full',
		'options' => array(
			'full' => __('Full', 'response'),
			'half' => __('Half', 'response'),
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Type', 'response'),
		'id' => 'blog_slider_type',
		'type' => 'select',
		'std' => 'posts',
		'options' => array(
			'posts' => __('Posts', 'response'),
			'custom' => __('Custom', 'response'),
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Post Categories', 'response'),
		'id' => 'blog_slider_post_cats',
		'type' => 'select',
		'std' => 'response_all',
		'options' => $options_categories,
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Number of Featured Blog Posts', 'response'),
		'id' => 'blog_no_featured_posts',
		'std' => '',
		'type' => 'text',
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Height', 'response'),
		'id' => 'blog_slider_height',
		'std' => '',
		'type' => 'text',
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Animation', 'response'),
		'id' => 'blog_slider_animation',
		'type' => 'select',
		'std' => 'horizontal-push',
		'options' => array(
			'horizontal-push' => __('Horizontal Push', 'response'),
			'fade' => __('Fade', 'response'),
			'horizontal-slide' => __('Horizontal Slide', 'response'),
			'vertical-slide' => __('Vertical Slide', 'reponse')
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Caption Style', 'response'),
		'id' => 'blog_slider_caption_style',
		'type' => 'select',
		'std' => 'bottom',
		'options' => array(
			'bottom' => __('Bottom', 'response'),
			'right' => __('Right', 'response'),
			'left' => __('Left', 'response'),
			'none' => __('None', 'reponse')
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Caption Animation', 'response'),
		'id' => 'blog_caption_animation',
		'type' => 'select',
		'std' => 'fade',
		'options' => array(
			'fade' => __('Fade', 'response'),
			'slide-open' => __('Slide Open', 'response'),
			'none' => __('None', 'response')
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Navigation', 'response'),
		'id' => 'blog_slider_navigation',
		'type' => 'select',
		'std' => 'dots',
		'options' => array(
			'dots' => __('Dots', 'response'),
			'thumbs' => __('Thumbnails', 'response'),
			'none' => __('None', 'response')
		),
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading',
	);
	
	$fields_list[] = array(
		'name' => __('Slider Arrows', 'response'),
		'id' => 'blog_slider_arrows',
		'type' => 'toggle',
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading'
	);
	
	/* TODO: Add in support
	$fields_list[] = array(
		'name' => __('Word Thumb Image Resizing', 'response'),
		'id' => 'blog_word_image_resizing',
		'type' => 'toggle',
		'section' => 'response_blog_slider_section',
		'heading' => 'response_blog_heading'
	);
	*/
	
	/*********** SEO *****************/
	
	$fields_list[] = array(
		'name' => __('Home Description', 'response'),
		'id' => 'seo_home_desc',
		'std' => '',
		'type' => 'textarea',
		'section' => 'response_blog_seo_section',
		'heading' => 'response_blog_heading');	
		
	$fields_list[] = array(
		'name' => __('Home Keywords', 'response'),
		'id' => 'seo_home_keywords',
		'std' => '',
		'type' => 'textarea',
		'section' => 'response_blog_seo_section',
		'heading' => 'response_blog_heading');	
		
	$fields_list[] = array(
		'name' => __('Optional Home Title', 'response'),
		'id' => 'seo_optional_title',
		'std' => '',
		'type' => 'text',
		'section' => 'response_blog_seo_section',
		'heading' => 'response_blog_heading',
	);
	
	/*************************************************************/
	/* TEMPLATES */
	/*************************************************************/
	
	/* SINGLE POSTS */
	
	$fields_list[] = array(
		'name' => __('Sidebar Options', 'response'),
		'desc' => __('Images for layout.', 'response'),
		'id' => 'single_post_sidebar_options',
		'std' => 'right_sidebar',
		'type' => 'images',
		'options' => array(
			'full_width' => $imagepath . '1col.png',
			'right_sidebar' => $imagepath . '2cr.png',
			'left_sidebar' => $imagepath . '2cl.png',
		),
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Breadcrumbs', 'response'),
		'id' => 'single_post_breadcrumbs',
		'type' => 'toggle',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Featured Images', 'response'),
		'id' => 'single_post_featured_images',
		'type' => 'toggle',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Format Icons', 'response'),
		'id' => 'single_post_format_icons',
		'type' => 'toggle',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Byline Elements', 'response'),
		'id' => 'single_post_byline_elements',
		'std' => $pbe_defaults, // These items get checked by default
		'type' => 'multicheck',
		'options' => $pbe_array,
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
		);

	$fields_list[] = array(
		'name' => __('Facebook Like Button', 'response'),
		'id' => 'single_post_facebook_like',
		'type' => 'toggle',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Google Plus One Button', 'response'),
		'id' => 'single_post_google_plus',
		'type' => 'toggle',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Pagination Links', 'response'),
		'id' => 'single_post_post_pagination',
		'type' => 'toggle',
		'section' => 'response_single_post_section',
		'heading' => 'response_templates_heading'
	);
	
	/* ARCHIVE */
	$fields_list[] = array(
		'name' => __('Sidebar Options', 'response'),
		'desc' => __('Images for layout.', 'response'),
		'id' => 'archive_sidebar_options',
		'std' => 'right_sidebar',
		'type' => 'images',
		'options' => array(
			'full_width' => $imagepath . '1col.png',
			'right_sidebar' => $imagepath . '2cr.png',
			'left_sidebar' => $imagepath . '2cl.png',
		),
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Breadcrumbs', 'response'),
		'id' => 'archive_breadcrumbs',
		'type' => 'toggle',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Featured Images', 'response'),
		'id' => 'archive_featured_images',
		'type' => 'toggle',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Format Icons', 'response'),
		'id' => 'archive_format_icons',
		'type' => 'toggle',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Byline Elements', 'response'),
		'id' => 'archive_post_byline_elements',
		'std' => $pbe_defaults, // These items get checked by default
		'type' => 'multicheck',
		'options' => $pbe_array,
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
		);

	$fields_list[] = array(
		'name' => __('Facebook Like Button', 'response'),
		'id' => 'archive_facebook_like',
		'type' => 'toggle',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Google Plus One Button', 'response'),
		'id' => 'archive_google_plus',
		'type' => 'toggle',
		'section' => 'response_archive_section',
		'heading' => 'response_templates_heading'
	);
	
	/* SEARCH */
	$fields_list[] = array(
		'name' => __('Sidebar Options', 'response'),
		'desc' => __('Images for layout.', 'response'),
		'id' => 'search_sidebar_options',
		'std' => 'right_sidebar',
		'type' => 'images',
		'options' => array(
			'full_width' => $imagepath . '1col.png',
			'right_sidebar' => $imagepath . '2cr.png',
			'left_sidebar' => $imagepath . '2cl.png',
		),
		'section' => 'response_search_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Post Excerpts', 'response'),
		'id' => 'search_post_excerpts',
		'type' => 'toggle',
		'section' => 'response_search_section',
		'heading' => 'response_templates_heading'
	);
	
	/* 404 */
	$fields_list[] = array(
		'name' => __('Sidebar Options', 'response'),
		'desc' => __('Images for layout.', 'response'),
		'id' => 'error_sidebar_options',
		'std' => 'full_width',
		'type' => 'images',
		'options' => array(
			'full_width' => $imagepath . '1col.png',
			'right_sidebar' => $imagepath . '2cr.png',
			'left_sidebar' => $imagepath . '2cl.png',
		),
		'section' => 'response_error_section',
		'heading' => 'response_templates_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Custom 404 Content', 'response'),
		'id' => 'error_custom_content',
		'std' => '',
		'type' => 'textarea',
		'section' => 'response_error_section',
		'heading' => 'response_templates_heading'
	);
	
	/************************************************************************************/
	/* FOOTER */
	/************************************************************************************/
	
	$fields_list[] = array(
		'name' => __('Footer', 'response'),
		'id' => 'footer_toggle',
		'type' => 'toggle',
		'section' => 'response_footer_section',
		'heading' => 'response_footer_heading'
	);
	
	$fields_list[] = array(
		'id' => 'footer_copyright_text',
		'name' => __('Footer Copyright Text', 'response'),
		'std' => '',
		'type' => 'text',
		'section' => 'response_footer_section',
		'heading' => 'response_footer_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Cyberchimps Link', 'response'),
		'id' => 'footer_cyberchimps_link',
		'type' => 'toggle',
		'section' => 'response_footer_section',
		'heading' => 'response_footer_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Afterfooter', 'response'),
		'id' => 'afterfooter_toggle',
		'type' => 'toggle',
		'section' => 'response_footer_section',
		'heading' => 'response_footer_heading'
	);
	
	/****************************************************************/
	/* IMPORT EXPORT */
	/***************************************************************/
	
	$fields_list[] = array(
		'name' => __('Export Settings', 'response'),
		'id' => 'export_textarea',
		'std' => '',
		'type' => 'textarea',
		'section' => 'response_import_export_section',
		'heading' => 'response_import_export_heading'
	);
	
	$fields_list[] = array(
		'name' => __('Import Settings', 'response'),
		'id' => 'import_textarea',
		'std' => '',
		'type' => 'textarea',
		'section' => 'response_import_export_section',
		'heading' => 'response_import_export_heading'
	);
	
	return $fields_list;
}
add_filter('response_field_list', 'response_add_core_fields');