<?php
/**
 * Class Cyberchimps_Meta_Box
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */


class Cyberchimps_Meta_Box {

    public $sections;
    public $fields;

    public function __construct( $sections, $fields ) {
        $this->sections = $sections;
        $this->fields = $fields;
    }

    public function render_display() {
        wp_nonce_field(basename(__FILE__), 'cyberchimps_meta_box_nonce');

        foreach( $this->sections as $section ) {
            $fields = $this->fields;

            add_meta_box( $section['id'], $section['title'], array( &$this, 'render_section'), $section['post_type'], $section['context'], $section['priority'], array( $fields[$section['id']] ) );
        }
    }

    public function render_section( $post, $args ) {
        global $post;

        echo '<table class="form-table">';
        foreach( $args['args'] as $field ) {
            $meta = get_post_meta($post->ID, $field['id'], !(isset($field['multiple']) && $field['multiple']));
            $meta = (!empty($meta) || $meta === "0" ) ? $meta : (isset($field['std']) ? $field['std'] : '');

            $this->field_start( $field );
            call_user_func(array(&$this, 'input_' . $field['type']), $field, $meta );
            $this->field_end();
        }
        echo '</table>';
    }

    public function render_fields(){

    }

    protected function field_start( $args ) {
        echo "<tr><th style='width: 20%'><label for='{$args['id']}'>{$args['title']}</label></th><td>";
    }

    protected function field_end() {
        echo '</td></tr>';
    }
    protected function input_text( $args ) {
        echo "<input type='text' name='{$args['id']}' id='{$args['id']}' value='' size='30' style='width:60%' />";
    }
}