<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// FIXME: Fix documentation
function response_before_header() {
	do_action('response_before_header');
}

// FIXME: Fix documentation
function response_filter_content_class( $display = true) {
	$output = sanitize_html_class( apply_filters('response_filter_content_class', 'span9') );
	
	if (!$display)
		return $output;
	
	echo $output;
}

// FIXME: Fix documentation
function response_filter_container_class( $display = true) {
	$output = sanitize_html_class( apply_filters('response_filter_container_class', 'row-fluid') );
	
	if (!$display)
		return $output;
	
	echo $output;
}