<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// FIXME: Fix documentation
function cyberchimps_before_header() {
	do_action('cyberchimps_before_header');
}

function cyberchimps_add_sidebar_left() {
	get_sidebar( 'left' );
}

function cyberchimps_add_sidebar_right() {
	get_sidebar( 'right' );
}

// FIXME: Fix documentation
// TODO: Find a way to compress or replicate all of these functions
function cyberchimps_class_container_fluid( $classes ) {
	$classes[] = 'container-fluid';
	return $classes;
}
function cyberchimps_class_row_fluid( $classes ) {
	$classes[] = 'row-fluid';
	return $classes;
}
function cyberchimps_class_span12( $classes ) {
	$classes[] = 'span12';
	return $classes;
}
function cyberchimps_class_span11( $classes ) {
	$classes[] = 'span11';
	return $classes;
}
function cyberchimps_class_span10( $classes ) {
	$classes[] = 'span10';
	return $classes;
}
function cyberchimps_class_span9( $classes ) {
	$classes[] = 'span9';
	return $classes;
}
function cyberchimps_class_span8( $classes ) {
	$classes[] = 'span8';
	return $classes;
}
function cyberchimps_class_span7( $classes ) {
	$classes[] = 'span7';
	return $classes;
}
function cyberchimps_class_span6( $classes ) {
	$classes[] = 'span6';
	return $classes;
}
function cyberchimps_class_span5( $classes ) {
	$classes[] = 'span5';
	return $classes;
}
function cyberchimps_class_span4( $classes ) {
	$classes[] = 'span4';
	return $classes;
}
function cyberchimps_class_span3( $classes ) {
	$classes[] = 'span3';
	return $classes;
}
function cyberchimps_class_span2( $classes ) {
	$classes[] = 'span2';
	return $classes;
}
function cyberchimps_class_span1( $classes ) {
	$classes[] = 'span1';
	return $classes;
}

// FIXME: Fix documentation
add_filter( 'cyberchimps_content_class', 'cyberchimps_default_content_classes');
function cyberchimps_default_content_classes( $classes ) {
	$classes[] = '';
	return $classes;
}

// FIXME: Fix documentation
function cyberchimps_filter_content_class( ) {
	// Separates classes with a single space, collates classes for content element
	echo 'class="' . esc_attr( join( ' ', apply_filters( 'cyberchimps_content_class', array() ) ) ) . '"';
}

// FIXME: Fix documentation
add_filter( 'cyberchimps_container_class', 'cyberchimps_default_container_classes');
function cyberchimps_default_container_classes( $classes ) {
	$classes[] = 'row-fluid';
	return $classes;
}

// FIXME: Fix documentation
function cyberchimps_filter_container_class( ) {
	// Separates classes with a single space, collates classes for content element
	echo 'class="' . esc_attr( join( ' ', apply_filters( 'cyberchimps_container_class', array() ) ) ) . '"';
}


// FIXME: Fix documentation
add_filter( 'cyberchimps_sidebar_left_class', 'cyberchimps_default_sidebar_left_classes');
function cyberchimps_default_sidebar_left_classes( $classes ) {
	$classes[] = 'widget-area';
	return $classes;
}

// FIXME: Fix documentation
function cyberchimps_filter_sidebar_left_class( ) {
	// Separates classes with a single space, collates classes for content element
	echo 'class="' . esc_attr( join( ' ', apply_filters( 'cyberchimps_sidebar_left_class', array() ) ) ) . '"';
}

// FIXME: Fix documentation
add_filter( 'cyberchimps_sidebar_right_class', 'cyberchimps_default_sidebar_right_classes');
function cyberchimps_default_sidebar_right_classes( $classes ) {
	$classes[] = 'widget-area';
	return $classes;
}

// FIXME: Fix documentation
function cyberchimps_filter_sidebar_right_class( ) {
	// Separates classes with a single space, collates classes for content element
	echo 'class="' . esc_attr( join( ' ', apply_filters( 'cyberchimps_sidebar_right_class', array() ) ) ) . '"';
}