<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

function cyberchimps_init_slides_post_type() {
	register_post_type( 'custom_slides',
		array(
			'labels' => array(
				'name' => __( 'Slides', 'cyberchimps'),
				'singular_name' => __( 'Slides', 'cyberchimps'),
				// TODO: Fix Labels
			),
			'public' => true,
			'show_ui' => true,
			'supports' => array('custom-fields', 'title'),
			'taxonomies' => array( 'slide_categories'),
			'has_archive' => true,
			'menu_icon' => get_template_directory_uri() . '/cyberchimps/lib/images/custom-types/slider.png',
			'rewrite' => array('slug' => 'slides')
		)
	);
	
	$labels = array(
    'name' => _x( 'Slide Categories', 'taxonomy general name' ),
    'singular_name' => _x( 'Slide Catergory', 'taxonomy singular name' ),
    'search_items' =>  __( 'Search Slides' ),
    'all_items' => __( 'All Slides' ),
    'parent_item' => __( 'Slide Category' ),
    'parent_item_colon' => __( 'Slide Category:' ),
    'edit_item' => __( 'Edit Slide Category' ), 
    'update_item' => __( 'Update Slide Category' ),
    'add_new_item' => __( 'Add New Slide Category' ),
    'new_item_name' => __( 'New Slide Category Name' ),
    'menu_name' => __( 'Slide Category' ),
  ); 	
	register_taxonomy( 'slide_categories', array('custom_slides'), array(
		'public' => true,
		'show_in_nav_menus' => false,
    'hierarchical' => true,
    'labels' => $labels,
    'show_ui' => true
  ));
		
	$meta_boxes = array();
	
	$mb = new Chimps_Metabox('slides', 'Custom Feature Slides', array('pages' => array('custom_slides')));
	$mb
		->tab("Custom Slide Options")
			->text('slider_caption', 'Custom Slide Caption', '')
			->text('slider_url', 'Custom Slide Link', '')
			->single_image('cyberchimps_slider_image', 'Custom Slide Image', '')
			->checkbox('slider_hidetitle', 'Slide Title Bar', '', array('std' => 'on'))
			->single_image('slider_custom_thumb', 'Custom Thumbnail', '')
			->sliderhelp('', 'Need Help?', '')
			->reorder('reorder_id', 'Reorder Name', 'Reorder Desc' )
		->end();
}
add_action( 'init', 'cyberchimps_init_slides_post_type' );