<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

/**
* Adds the CyberChimps credit.
*
* @since 1.0
*/
function response_footer_credit() { 

	if (response_get_option('footer_cyberchimps_link') == '1') { ?>
		<div id="credit" class="span6">
			<a href="http://cyberchimps.com/" target="_blank"><img src="<?php echo get_template_directory_uri(); ?>/core/lib/images/achimps.png" alt="credit" /></a>
		</div>
	<?php }
}
add_action ( 'response_footer', 'response_footer_credit' );

/**
* Adds the afterfooter copyright area. 
*
* @since 1.0
*/
function response_footer_copyright() {

	if ( response_get_option('footer_copyright_text') ) {
		$copyright = response_get_option('footer_copyright_text');
	} else {
		$copyright = get_bloginfo('name');
	}

	echo '<div id="footer-copyright" class="span6">';
	echo "&copy; $copyright";
	echo '</div>';
}
add_action ( 'response_footer', 'response_footer_copyright' );